### ISSUE TITLE
Show variables in different formats

### ISSUE THREAD

**Issue by gabbayo** [cs01/gdbgui#102]
Hi,
I'm currently trying your tool - great work!
However, I'm trying to view variables in different format then decimal and I can't do it. 
e.g. I have a variable that is defined as unsigned long. When I hover above it or when I look in the local variables window, I see its value as decimal. However, I would like to see its value in hex.
Is this supported or not ?
If not, can you please try to add it ? It's very useful feature, IMO.

Thanks,
Oded

**Comment by cs01** [comment]
Thanks using gdbgui and thanks for the suggestion. I can see how it would be useful. That is definitely something I can do.  I think I'll add a dropdown that allows you to specify decimal, hex, and octal for the base of all the numerical values.
