### ISSUE TITLE
auto-completion in embedded gdb console window

### ISSUE THREAD

**Issue by gabbayo** [cs01/gdbgui#103]
Is there a shortcut to support the auto-completion in the gdb console window at the bottom of the screen ? 
When running gdb, you can press TAB and it auto-completes variables, function names, etc.
However, in the browser (at least in chrome), it moves the focus to another place in the browser window.

**Comment by cs01** [comment]
This would definitely be cool. I think the issue is a little more complicated than the browser moving focus -- that much is easy enough to fix. What I don't know how to do is send a command to gdb-mi to get it to list completions. I can ask in the #gdb irc room.

**Comment by bobthekingofegypt** [comment]
I could have a look at adding this for you if you want.

Passing the complete command to gdb(-mi) should return a list of completions as far as I am aware.

```
(gdb) complete br
break
break-range
```

gdb in interpreter=mi2 mode
```
(gdb) 
complete br
&"complete br\n"
~"break\n"
~"break-range\n"
^done
(gdb)
```

**Comment by cs01** [comment]
Oh wow this is perfect, thanks for sharing.  I can implement this with the new info you gave me, assuming it works like you described.  If you *want* to add it, I will not turn down the pull request, but it shouldn't be too hard for me to add in. Let me know which you'd prefer so we aren't working in parallel.  

Did you get your other issue resolved?

**Comment by bobthekingofegypt** [comment]
I'm happy to look at doing it.  

One question though, is your plan to move everything over to react components rendering with jsx?

No not yet, was just looking for an issue to pick up to look at how the project is working.

**Comment by cs01** [comment]
Yes, the plan is that eventually everything will be react/jsx. The gdb console isn't react, so that increases the scope of the work a bit.
