### ISSUE TITLE
add button to attach to process/thread group

### ISSUE THREAD

**Issue by cs01** [cs01/gdbgui#104]
Although it's possible to attach to a process, thread group, or file via the command line widget, it would be helpful to add a button to do so.

The task is to add a button to execute the following gdb-mi command:
`-target-attach pid | gid | file`
https://www.sourceware.org/gdb/onlinedocs/gdb/GDB_002fMI-Target-Manipulation.html

**Comment by paulorb** [comment]
Are you guys able to use attach? I tried to attach but it is giving me error "timeout gdb is not responding"

**Comment by cs01** [comment]
Does it attach and then not respond after subsequent commands? If so, try running gdbgui as `sudo`.

**Comment by paulorb** [comment]
Yes it works fine, thanks.

**Comment by vineethkartha** [comment]
Hi 
I would love to take a shot at this issue.

Regards
Vineeth

**Comment by cs01** [comment]
If you would like to try that would be super cool.  Give it a go, let me know if you have any questions.

**Comment by vineethkartha** [comment]
I am facing a couple of issues with setting up the dev-environment. I followed the steps in the 
and on running npm install , I get the following:

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.3
npm WARN optional Skipping failed optional dependency /sane/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.3
npm WARN gdbgui@0.1.0 No repository field.
npm ERR! Linux 4.10.0-40-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.7.2
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! uglifyjs-webpack-plugin@0.4.6 postinstall: `node lib/post_install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the uglifyjs-webpack-plugin@0.4.6 postinstall script 'node lib/post_install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the uglifyjs-webpack-plugin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/post_install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs uglifyjs-webpack-plugin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls uglifyjs-webpack-plugin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/kartha/Projects/gdbgui/npm-debug.log

**Comment by vineethkartha** [comment]
I just had a design question, Do you think it would be better to create a new class for the attach process like the BinaryLoader, or is it just enough to add button in the btn-group ?

**Comment by cs01** [comment]
I think the best way to add this would be to leave as is since loading a binary is probably the most common use case.  Then and add a small drop down button to the left of the load binary button that shows a list of the other options. At this time it would just be the "attach to process/thread group". When that is selected the placeholder text would be updated and the button text would be updated.
