### ISSUE TITLE
Key Arrows right behavior differ from letter "n" behavior

### ISSUE THREAD

**Issue by Ghom** [cs01/gdbgui#108]
I am debugging using a cross compiled gdb to remotly debug a R-CarH3 board from a distant linux computer. I then use my local computer under windows to access the gdbgui server. So basically Windows (browser connecting to gdbgui) -> Linux (running gdbgui) -> RcarH3 (running the binary to debug). 
However when I use the function next of GDB using you keyboard shortcut "n" everything works fine but when i use the right arrow it does crash at a certain point. 

also when GDB ask to quit the debug session the answer is "Y" instead of "y". 
Those issue are not related to gdb itself because the same procedure works when I am not hoocked to gdbgui. 

The command I use to run gdbgui is: gdbgui -r -g /path/to/my/gdb/ntoaarch64-gdb "my_bin"

here is the error output:
`Selected thread is running.
*stopped
../../gdb/infcall.c:1373: internal-error: value* call_function_by_hand_dummy(value*, int, value**, void (*)(void*, int), void*): ... should not be here
A problem internal to GDB has been detected,
further debugging may prove unreliable.
Quit this debugging session? 
(y or n) [answered Y; input not from terminal]
../../gdb/infcall.c:1373: internal-error: value* call_function_by_hand_dummy(value*, int, value**, void (*)(void*, int), void*): ... should not be here
A problem internal to GDB has been detected,
further debugging may prove unreliable.
Create a core file of GDB? 
(y or n) [answered Y; input not from terminal]
Error occurred on server when running gdb command: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gdbgui/backend.py", line 191, in run_gdb_command
    _gdb_state['gdb_controllers'].get(request.sid).write(cmd, read_response=False)
  File "/usr/local/lib/python2.7/dist-packages/pygdbmi/gdbcontroller.py", line 118, in write
    self.verify_valid_gdb_subprocess()
  File "/usr/local/lib/python2.7/dist-packages/pygdbmi/gdbcontroller.py", line 94, in verify_valid_gdb_subprocess
    raise NoGdbProcessError('gdb process has already finished with return code: %s' % str(self.gdb_process.poll()))
NoGdbProcessError: gdb process has already finished with return code: -6`

pip freeze:
adium-theme-ubuntu==0.3.4
apt-xapian-index==0.45
chardet==2.0.1
click==6.7
command-not-found==0.3
debtagshw==0.1
defer==1.0.6
dirspec==13.10
duplicity==0.6.23
enum-compat==0.0.2
enum34==1.1.6
eventlet==0.21.0
Flask==0.12.2
Flask-SocketIO==2.9.2
gdbgui==0.7.9.5
gevent==1.2.2
greenlet==0.4.12
httplib2==0.8
itsdangerous==0.24
Jinja2==2.9.6
lockfile==0.8
lxml==3.3.3
MarkupSafe==1.0
oauthlib==0.6.1
oneconf==0.3.7.14.4.1
PAM==0.4.2
pexpect==3.1
Pillow==2.3.0
piston-mini-client==0.7.5
pycrypto==2.6.1
pycups==1.9.66
pygdbmi==0.7.4.1
Pygments==2.2.0
pygobject==3.12.0
pyOpenSSL==0.13
pypugjs==4.2.2
pyserial==2.6
pysmbc==1.0.14.1
python-apt===0.9.3.5ubuntu1
python-debian===0.1.21-nmu2ubuntu2
python-engineio==1.7.0
python-socketio==1.8.0
pyxdg==0.25
reportlab==3.0
requests==2.2.1
sessioninstaller==0.0.0
six==1.10.0
software-center-aptd-plugins==0.0.0
ssh-import-id==3.21
system-service==0.1.6
Twisted-Core==13.2.0
Twisted-Web==13.2.0
unity-lens-photos==1.0
urllib3==1.7.1
Werkzeug==0.12.2
xdiagnose===3.6.3build2
zope.interface==4.0.5

uname -a:
3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

browser:
Google Chrome Version 60.0.3112.101 (Official Build) (64-bit)

gdbgui -v:
0.7.9.5

gdb -v:
GNU gdb (GDB) 7.12 [qnx700 r1234]
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "--host=x86_64-pc-linux-gnu --target=aarch64-unknown-nto-qnx7.0.0".
Type "show configuration" for configuration details.Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".

I hope this help you to improve gdbgui.

**Comment by cs01** [comment]
Thanks for the issue report. 

Regarding the `n` key vs the right arrow: There is no difference in how this code is handled in [gdbgui.js](https://github.com/cs01/gdbgui/blob/master/gdbgui/static/js/gdbgui.js#L3518):
```javascript
            }else if(e.keyCode === RIGHT_BUTTON_NUM || char === 'n'){
                GdbApi.click_next_button()
```
so I am not sure how it would cause different errors. 

However, I can see from the output that gdb is crashing, which causes gdbgui to stop working:
>Selected thread is running. *stopped ../../gdb/infcall.c:1373: internal-error: value* call_function_by_hand_dummy(value*, int, value**, void (*)(void*, int), void*): ... should not be here A problem internal to GDB has been detected, further debugging may prove unreliable. Quit this debugging session? (y or n) [answered Y; input not from terminal] ../../gdb/infcall.c:1373: internal-error: value* call_function_by_hand_dummy(value*, int, value**, void (*)(void*, int), void*): ... should not be here A problem internal to GDB has been detected, further debugging may prove unreliable. Create a core file of GDB? (y or n) [answered Y; input not from terminal]

> also when GDB ask to quit the debug session the answer is "Y" instead of "y".
Those issue are not related to gdb itself because the same procedure works when I am not hoocked to gdbgui.

I would recommend running the command 
```
set confirm off
```
(https://sourceware.org/gdb/current/onlinedocs/gdb/Messages_002fWarnings.html) which will avoid the lowercase `y` vs uppercase `Y` confusion. (Just for the record, `gdbgui` does not answer `y` or `Y`, that's sometihng `gdb` does itself). Please let me know if that helps.
