### ISSUE TITLE
xmm register values not displayed (probable GDB 8.0 bug)

### ISSUE THREAD

**Issue by pcordes** [cs01/gdbgui#109]
I'm on x86-64 Arch Linux (rolling release, updated last week), using python-gdbgui 0.7.9.5-1 built from https://aur.archlinux.org/packages/python-gdbgui/.

I have gdb 8.0 (from the Arch binary package), and my browser is Chromium 60.0.3112.101 (Developer Build) (64-bit) from the Arch binary package.  Linux kernel 4.12.8-2-ARCH.

----

I'm single-stepping through PLT lazy dynamic linker code that resolves `puts`, when called from `main` in a hello world program (just to see how well fetch disassembly mode works).  I compiled it with `gcc -O3 -g` (gcc7.1.1) for x86-64.

The "registers" dropdown has blank entries for xmm0-xmm15.  It shows zeros for ymm0-ymm15 (which is correct.)

gdb's own `tui` mode (`layout reg`  / `tui reg vector`) has a similar problem when I use gdb stand-alone: It shows just blank space for the ymm register values.  However, `p /x $xmm0.v4_int32` shows non-zero values in vanilla gdb and in gdbgui's console.

**I just realized this might all be a GDB bug, if the `mi2` command responses are bogus the same way the `tui` register pane is**.  Those could both be broken in gdb while console commands were unaffected.

gdbgui does correctly show the high lane, e.g. after `set $ymm5.v4_int64 = {0xffff, 0xffff, 0xffff, 0xffff}` I can see what I expect.  But `xmm5` is still blank.

MXCSR (the SSE control/status register) is sometimes changing to a non-zero value and then going back to `0` on instructions like `push` (which can't modify MSCSR).  The value displayed matches what I see from typing `p /x $mxcsr`, but that's clearly bogus because it means all exceptions are unmasked.  (A normal value for MXCSR is something like 0x1F80, which is the state when the machine boots.  See also https://software.intel.com/en-us/articles/x87-and-sse-floating-point-assists-in-ia-32-flush-to-zero-ftz-and-denormals-are-zero-daz).

However, I also see this in the `tui reg vector` pane.

Similarly, `fctrl`, `fstat`, and the other x87 status/control registers are spuriously changing when stepping over integer instructions.

I'm on a Skylake i7-6700k CPU, which supports MPX, so maybe gdb is getting confused by the presence of `bnd` registers?  `bnd0raw` 0-3 are also shown as blank in gdbgui.

These problems were all happening even before stepping over a `bnd` and `xgetbv` instruction in the dynamic-linker code, but maybe on a target that supports MPX, the layout of some struct changes to hold new registers, and that's the source of problems with both `tui reg` and the `--interpreter=mi2` interface?

**Comment by cs01** [comment]
If you run gdbgui with the `--debug` flag, a new widget is added at the bottom of the right pane that lets you  view the raw gdb mi output before it's displayed by gdbgui in the other UI elements. If you look at that and the xmm registers are blank, then it's a gdb bug. If they aren't, then it's a gdbgui bug.

You can also ask the question in the [gdb IRC channel](https://www.gnu.org/software/gdb/irc/), they may be able to help.

**Comment by cs01** [comment]
I would suggest you file this in gdb's bug tracker. I'm going to close here. Let me know if you have any objections. Thanks for filing the issue.

**Comment by pcordes** [comment]
Yeah, seems to be just a gdb bug.  Perhaps gdbgui could work around it with gdb `print` commands (which do still work), but that seems like a waste of effort compared to getting it fixed upstream.

Reported upstream as https://sourceware.org/bugzilla/show_bug.cgi?id=22704.
