### ISSUE TITLE
GUI option for  set disassembly-flavor intel?

### ISSUE THREAD

**Issue by pcordes** [cs01/gdbgui#110]
I use `set disassembly-flavor intel` in my ~/.gdbinit.  I don't see an equivalent feature in gdbgui.  (And it doesn't read .gdbinit).

I can type  `set disassembly-flavor intel` (or `att`) in the console pane, and it updates next time the pane changes to a new location.

(reload file / hide disassembly  isn't hiding it or re-fetching it in the other format, though.  I'm looking at a function that doesn't have source, so it's *just* the disassembly)

Matt Godbolt's compiler-explorer (http://gcc.godbolt.org) does this nicely: there's an `intel` button that you can toggle.

**Comment by cs01** [comment]
Cool idea, I can look into adding this

**Comment by cs01** [comment]
FYI with gdbgui 0.8.1.0 I got this to work via the console by running `set disassembly-flavor intel`, then refetching the source. So I've confirmed it works, all I need to do is add the button. I will add it when I get the time.

**Comment by cs01** [comment]
this is available in 0.9.0.0
