### ISSUE TITLE
File not found: /Users/travis/build/rust-lang/rust/src/liballoc/heap.rs

### ISSUE THREAD

**Issue by adrianbrink** [cs01/gdbgui#112]
When I compile a rust program and start it with `gdbgui /path/to/exec` it always throws me this error no matter what the binary. This is an executable with a main function.

Btw, is it possible to test libraries or only binaries?

**Comment by cs01** [comment]
Not sure why. I'm not getting it when running the [Rust example](https://github.com/cs01/gdbgui/tree/master/examples/rust). It sounds like it might be a gdb issue. Rust support is still sort of nascent in gdb, but it's coming along.

You can try submitting a [bug on gdb itself](https://www.gnu.org/software/gdb/bugs/), or asking the question in the [IRC channel](https://www.gnu.org/software/gdb/irc/).
