### ISSUE TITLE
Support for python

### ISSUE THREAD

**Issue by Vic-Wu** [cs01/gdbgui#114]
How about the schedule for supporting debug python code?

**Comment by cs01** [comment]
I'm assuming you mean debugging python code through the gdbgui frontend. There is no plan to support this. You may find https://github.com/Kozea/wdb already does what you want.

**Comment by Vic-Wu** [comment]
Yes, I'm using wdb. But, I think gdbgui is better and I wish I can debug my pythoin code with it. 
Thanks.

**Comment by cs01** [comment]
Glad you like it. If you want to try and branch `gdbgui` to `pdbgui`, you're welcome to, but I'm afraid I don't have the bandwidth to take that on myself.

**Comment by anirudh2290** [comment]
If you have c++ backend with python frontend you should be able to debug it with gdbgui.
