### ISSUE TITLE
gdb does not stop at breakpoint

### ISSUE THREAD

**Issue by melhindi** [cs01/gdbgui#115]
Hi,

when I run the debugger via gdbgui it does not stop at the breakpoint.

I assume this is because I have not installed gdb with the "with-python" option (just brew install gdb)
I did this because the installation with "with-python" fails saying "configure: error: no usable python found at /usr/local" although python and python3 has been correctly installed.

My system is Mac OS Sierra (10.12.6)

**Comment by cs01** [comment]
Hi, thanks for the issue report.

Have you tried searching for solutions on how to install gdb with python using brew? Surely someone must have figured out how to do this. A quick search yielded this, which may help: 

```
 brew -v install --with-python gdb
```
https://stackoverflow.com/a/23670214/2893090

**Comment by melhindi** [comment]
Hi thanks for the answer,

yes I searched for a solution, but could not find one.  One think, I am looking into, is the following hint that I observed from brew this time:
"These open issues may also help:
gdb: fix Add python3 linkage support https://github.com/Homebrew/homebrew-core/pull/17979"

I am just wondering if I am the only one seeing this
