### ISSUE TITLE
Spaces in file paths does not allow executable to load

### ISSUE THREAD

**Issue by humdogm** [cs01/gdbgui#116]
When I attempt to load a file with a file path that contains spaces, gdbgui returns an error: No such file or directory. From what I see in the console, it automatically assumes that anything following a space in the file path is an exec-argument instead of as a part of file-exec-and-symbols. Even when I escape the spaces by placing a backslash (\) before them I see the exact same behavior. Please allow for escaping spaces found in the file path. 

[pip freeze](https://github.com/cs01/gdbgui/files/1304779/pipfreeze.txt)
Kali Linux 3.8.11 #1 SMP Wed Aug 16 21:51:30 PDT 2017 armv7l GNU/Linux
gdbgui version 0.7.9.5
gdb version: GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
Using Firefox ESR 52.3.0 32-bit

**Comment by cs01** [comment]
Thanks, I'll look into this

**Comment by cs01** [comment]
this has been fixed in v0.9.0.0
