### ISSUE TITLE
It support OpenOCD ?

### ISSUE THREAD

**Issue by RozenAstrayChen** [cs01/gdbgui#124]
Hi. Does __gdbguiI__ support Openocd to debugger embedded device?
we always used __arm-none-eabi-gdb__  load ```.elf``` and  remoted localhost:3333.
Does gdbgui support ?

**Comment by cs01** [comment]
Yes, see [this video](https://www.youtube.com/watch?v=u4lP4f2xnEo) for a demonstration (the video is not mine).

**Comment by AndreaBorgia-Abo** [comment]
That video does not show (or link to) the cmdline used to start gdbgui or the contents of gdbinit. There is one unanswered question quite similar to mine: I can get gdbgui to talk directly to openocd connected to esp32 via jlink but I can't get it to load symbols from an ELF file.
Any tips?

**Comment by cs01** [comment]
Is `add-symbol-file` helpful?

> The add-symbol-file command reads additional symbol table information from the file filename. You would use this command when filename has been dynamically loaded (by some other means) into the program that is running. 

https://sourceware.org/gdb/onlinedocs/gdb/Files.html
https://stackoverflow.com/a/20383043/2893090

**Comment by JohannesMaier** [comment]
@AndreaBorgia-Abo Did you found a manual how to use the gdbgui with openocd? I can´t find any detailed instructions. 
Thanks!

**Comment by AndreaBorgia-Abo** [comment]
@JohannesMaier I haven't played with it in a long time, it's still in my todolist.

**Comment by kammce** [comment]
I don't mean to open this back up, but I'll see if I can figure out how I did this originally with gdbgui.

**Comment by kammce** [comment]
This is how I was able to get this to work with openocd

Run typical `openocd` command:
```
openocd  -s $OPENOCD_PATH/scripts/ -c "source [find interface/$DEBUG_DEVICE.cfg]" -f $OPENOCD_TARGET_SCRIPT 
```

Run gdbgui
```
pipx run gdbgui --gdb $PATH_TO_ARM_GDB
```

From the user interface do these in this order:

1. In the GDB console below put in `target remote :3333`. The interface will update accordingly
2. Go to "Load Binary" and find the path to your elf file and load it.
3. Done.

Hopefully this helps. Using the connect to gdb server doesn't seem to work for me usually.
