### ISSUE TITLE
Can't work on Red Hat 6.2

### ISSUE THREAD

**Issue by xzzh999** [cs01/gdbgui#125]
Hello, big cow! Greate work!
But when i run on Red Hat Enterprise Linux Server release 6.2 (Santiago), here is the print:

      [root@localhost cdm]# gdbgui
      Opening gdbgui in browser at http://127.0.0.1:5000
      exit gdbgui by pressing CTRL+C
      /usr/bin/xdg-open: line 402: htmlview: command not found

and the brower firefox opened succuessful but i can't debug, why?

Need u help! 3Q very much!

**Comment by xzzh999** [comment]
BTW, i both installed python 2.6 and python 2.7, and make the default cmd 'python' to python 2.7.

**Comment by cs01** [comment]
Which version of gdbgui are you running?

**Comment by xzzh999** [comment]
0.8.0.3

**Comment by cs01** [comment]
Thanks. That's good, it's the latest version.  

If there is no error in the terminal, I imagine you are getting one in the browser.  Can you open the browser developer console (ctrl+shift+i) in chrome, reload the page, and let me know what text, if any, is displayed?

Also, it might be helpful to see the output of "pip freeze". Using a virtual environment often helps too, if you aren't already.

**Comment by xzzh999** [comment]
@cs01 Thank you for reply! I use firefox, my app called `vcca`, my command is:  ```gdbgui -p 9000 'vcca -d'```,
i'm not use  a virtual environment for now, and here is the debug print:

       Warning: Unknown property 'box-shadow'.  Declaration dropped.
       Source File: http://127.0.0.1:9000/static/vendor/css/bootstrap.min.css
       Line: 5

       ...

       Warning: Expected color but found 'auto'.  Expected color but found '-webkit-focus-ring-color'.  
       Expected end of value but found '-webkit-focus-ring-color'.  Error in parsing value for 'outline'.  
       Declaration dropped.
       Source File: http://127.0.0.1:9000/static/vendor/css/bootstrap.min.css
       Line: 5

       ...

       Error: uncaught exception: [Exception... "Not enough arguments"  nsresult: "0x80570001 
       (NS_ERROR_XPC_NOT_ENOUGH_ARGS)"  location: "JS frame :: 
        http://127.0.0.1:9000/static/vendor/js/jquery.min.js :: anonymous :: line 2"  data: no]

       ...

       Error: jQuery is not defined
       Source File: http://127.0.0.1:9000/static/vendor/js/jquery.flot-0.8.3.min.js
       Line: 1

       Error: Bootstrap's JavaScript requires jQuery
       Source File: http://127.0.0.1:9000/static/vendor/js/bootstrap.min.js
       Line: 6

       Error: t is not a function
       Source File: http://127.0.0.1:9000/static/vendor/js/lodash.min.js
       Line: 10

       Error: Object.create is not a function
       Source File: http://127.0.0.1:9000/static/vendor/js/vis-4.20.1.min.js
       Line: 29

       Error: Object.create is not a function
       Source File: http://127.0.0.1:9000/static/vendor/js/awesomeplete.min.js
       Line: 2

      ...

      Error: Object.defineProperty is not a function
      Source File: http://127.0.0.1:9000/static/js/index.js?_=0.8.0.3
      Line: 1


It looks like a jquery problem ?  i'm not familiar with web program ...

**Comment by cs01** [comment]
What version of Firefox are you using?

**Comment by xzzh999** [comment]
I use the `redhat 6.2` system build-in firefox:  ```Mozilla Firefox 3.6.24, Copyright (c) 1998 - 2011 mozilla.org```, it's too old...

I tried `centos 7.2.1511` instead, and the firefox version is `Mozilla Firefox 45.4.0`, and everything goes fine.

**Comment by cs01** [comment]
Great glad you got it working.  Enjoy!
