### ISSUE TITLE
support gdb style --args parameters

### ISSUE THREAD

**Issue by grandinj** [cs01/gdbgui#126]
Use case: for debugging LibreOffice, we use something like:

    make CppunitTest_sc_filters_test CPPUNITTRACE="gdb --args"

and then the makefile takes care of setting up the env vars, and passing in the 20 params we need.

It would be nice to be able to substitute that with:

   make CppunitTest_sc_filters_test CPPUNITTRACE="gdbgui --args"

:-)

**Comment by cs01** [comment]
gdbgui does support arguments, but they have to be passed in quotes.

```gdbgui "exec --arg"``` 

for example, would work. Does that help? If not, can you explain more what you're looking for?

**Comment by grandinj** [comment]
Yeah, I'm being a little impertinent in expecting gdbgui to work exactly like gdb, so feel free to close this if you're not interested in supporting this :-)

I could in theory hack our makefiles to do the right thing with gdbgui, it would just be nice if I didn't have to do so. Our makefiles only allow me to set the first part of the command line, and then pass the rest of the command line as per invoking our unit tests.

So what I need is some way of calling gdbgui that makes gdbgui treat all of the following parameters as being the command and it's args.

**Comment by cs01** [comment]
I think I understand what you are asking for. I made a branch with a proposed fix. 

If you can, cloning `gdbgui`, then checking out the branch `support-args-flag` and running `gdbgui/backend.py --args ...`. If it does what you expect, let me know and I'll merge it to master.
