### ISSUE TITLE
Using gdbgui to debug servo

### ISSUE THREAD

**Issue by bobthekingofegypt** [cs01/gdbgui#127]
I tried to use gdbgui to debug servo, I can get it to successfully hit a break point but then it dies. When the break point hits the code appears in the main window at the correct line but as soon as it does servo crashes with no messages.  If you try to execute anything from inside gdbgui after this point you just receive a  "gdb process has already finished with return code: 139" error in the terminal.

Running gdbgui with
```
gdbgui "./target/debug/servo" -g /usr/bin/rust-gdb
```

Then adding a break point in the gdbgui gdb console and call "r &lt;some webpage&gt;"

I normally debug servo with tui mode in gdb like this and it works fine
```
rust-gdb -tui -q --args target/debug/servo
```

If there is some better information I could pass over please let me know, this project looks a lot better than tui mode so it would be great if I could get it to work.

pip freeze
```
click==6.7
enum-compat==0.0.2
eventlet==0.21.0
Flask==0.12.2
Flask-SocketIO==2.9.2
gdbgui==0.8.0.3
gevent==1.2.2
greenlet==0.4.12
itsdangerous==0.24
Jinja2==2.9.6
MarkupSafe==1.0
pygdbmi==0.7.4.3
Pygments==2.2.0
pypugjs==4.2.2
python-engineio==1.7.0
python-socketio==1.8.1
six==1.11.0
Werkzeug==0.12.2
```

Operating system is gentoo linux running 4.12.12 kernel.

gdbgui version = 0.8.0.3

Browser is chrome.

**Comment by cs01** [comment]
Thanks for the issue report. 

I have never heard of/tested rust-gdb. It's possible that its machine interface output is different from gdb's. Do you know if the tui mode uses machine interface output? If you run gdbgui with the debug flag, a new widget appears on the bottom right.  If you copy and past that output, I may be able to tell what's going on a little better.  

The other thing I'm curious about is why you are running with the r command.  Generally you can specify the executable and arguments in gdbgui just as you'd specify them on the command line, I.e. 'servo <some webpage>', then use the UI controls to run, step, continue, etc.

**Comment by bobthekingofegypt** [comment]
To be honest I don't have a clue what tui mode uses.

Here is the output from debug https://gist.github.com/bobthekingofegypt/da1cdff2dbcf6d82dab1d0fb24559365

No reason other than it's just what was outlined in their debugging documentation https://github.com/servo/servo/wiki/Debugging

**Comment by bobthekingofegypt** [comment]
Now I've had a chance to look at the projects code I have more of an idea of what it is doing so I could look at this.

It appears that my rust-gdb segfaults when issued the -data-list-register-values (info all-reg) command.  Not sure why that is yet, will try to look into it but it doesn't look like it is gdbgui's fault in any way.

**Comment by cs01** [comment]
https://github.com/cs01/gdbgui/issues/64

**Comment by bobthekingofegypt** [comment]
Yeah, starting to piece things together now; I'm getting old and slow these days.  Upgraded to gdb 8 yesterday after a rust persons advice.

The work around not working is not a problem with the version number, I believe it is a problem with gdbgui's flow.
The code to detect if you can or cannot run -data-list-register-values appears in the parsing code for -file-list-exec-source-files response.  But this command does not run on a default startup only when I try to interact with the source code bar, probably because I add my breakpoints from the console.  So the default value of true is always present when it hits the breakpoint and therefore it makes the call to list registers and segfaults.

There are actually a few more problems with running against servo, or maybe big rust programs:
* servo takes more than 3 seconds to fully start in debug mode so the 3 second timer is too short, maybe we could make it a configurable flag?
* requesting source takes a long time, not even sure how long on an executable as big as servo as its never finished
* rust gdb integration appears a little bit weird in 7.*, locals (or variables in mi) can contain duplicates so if you are in a function the function argument can be present with an arg value in its details but also again as a non function argument local.  This breaks the Locals component in RightBar as it violates Reacts unique key constraint when iterating over sorted_local_objs as they have duplicate keys.  Also children of a local can contain multiple annonymous values breaking the unique key constraint in GbdVariable when it iterates over children.  

I've been trying to use gdbgui for something I'm looking at just now so seeing how it goes, didn't notice these things using tui mode as standard commands like "info locals" for example do not have the same issues.  I think the rust/gdb story isn't perfect, I'd go with weird based on what I've been seeing.  Maybe 8 will be better will see when I get some time.

**Comment by cs01** [comment]
> servo takes more than 3 seconds to fully start in debug mode so the 3 second timer is too short, maybe we could make it a configurable flag?

Before this timer existed, someone said they waited for 5 minutes for a response once. They had no idea nothing was going on "behind the scenes" and that an error occurred and no response was ever coming. So I figured some kind of timer would be appropriate. The 3 second number was sort of arbitrary. I can update the text to have some caveats to say it's not necessarily an error, and perhaps make it 10 seconds instead of 3.  It *could* be a configurable thing, but I think I'd rather hold off on adding configuration options for every little thing and try to get the behavior helpful in all situations, including #128 . 

> requesting source takes a long time, not even sure how long on an executable as big as servo as its never finished

I agree large file sizes can cause gdbgui to freeze, and I don't think this is a rust-specific problem. I have been thinking about how to handle this and created issue #131. Take a look and add comments there if you're interested.

> rust gdb integration appears a little bit weird in 7.*, locals (or variables in mi) can contain duplicates so if you are in a function the function argument can be present with an arg value in its details but also again as a non function argument local. This breaks the Locals component in RightBar as it violates Reacts unique key constraint when iterating over sorted_local_objs as they have duplicate keys. Also children of a local can contain multiple annonymous values breaking the unique key constraint in GbdVariable when it iterates over children.

Good feedback, though I don't generally develop in rust. The (very simple) [example](https://github.com/cs01/gdbgui/blob/master/examples/rust/hello.rs) in gdbgui looks fine when I step through it. Perhaps you can post some example code that fails as you described.

**Comment by cs01** [comment]
I'm going to close this issue since you determined the segfault was due to a gdb mi bug. If there are other unrelated issues, please create another issue and we can work it from there. Thanks again for your contribution of autocomplete! Very helpful! I added some screenshots and added it to gdbgui's description.
