### ISSUE TITLE
Add support for a login page to gdbui server

### ISSUE THREAD

**Issue by nickamon** [cs01/gdbgui#132]
I'm interested in using this wonderful tool on a school project on a remote machine that is shared with my fellow classmates.  Any thoughts on adding support for a login page?

**Comment by nickamon** [comment]
Seems like it should be relatively easy to add global basic password auth ...

https://stackoverflow.com/questions/12273096/global-function-to-authenticate-user-sessions-in-pythons-flask

**Comment by nickamon** [comment]
I was able to do it with a slightly different method, if you think this would be widely useful, let me know and I'll send a pull request.

**Comment by cs01** [comment]
It seems useful, I'd like to see it. Can you show me the branch?

**Comment by nickamon** [comment]
#133

**Comment by cs01** [comment]
Nice work, thank you!
