### ISSUE TITLE
no source code or assembly to display after running backtrace

### ISSUE THREAD

**Issue by pdewilde** [cs01/gdbgui#134]
I just updated gdbgui to the latest version, and all of the sudden it stopped displaying source code when doing a backtrace. While it properly finds the path to the source (the text above the source window is properly populated), the source window says "no source code or assembly to display", even though this worked just fine before updating.

**Comment by cs01** [comment]
Thanks for reporting the issue, I was not aware of this.  I'll check it out.

**Comment by cs01** [comment]
this has been fixed in `0.8.2.0`
