### ISSUE TITLE
gdbgui does not start under cygwin and windows 7

### ISSUE THREAD

**Issue by aha79** [cs01/gdbgui#139]
Hello!

I tried to run gdbgui from source in a cygwin64 environment on Windows 7. However gdbgui terminates itself:

```
$ python3 gdbgui/backend.py --debug
failed to initialize socketio app with async mode "eventlet". Continuing with async mode "threading".
View gdbgui at http://127.0.0.1:5000
exit gdbgui by pressing CTRL+C
WebSocket transport not available. Install eventlet or gevent and gevent-websocket for improved performance.
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
failed to initialize socketio app with async mode "eventlet". Continuing with async mode "threading".
View gdbgui at http://127.0.0.1:5000
exit gdbgui by pressing CTRL+C
WebSocket transport not available. Install eventlet or gevent and gevent-websocket for improved performance.
 * Debugger is active!
 * Debugger PIN: 185-489-695

```
Here the phyton3 interpreter terminates and the shell prompt returns. The source code is from GitHub as of today. I encountered the same problem already a few weeks ago (with python package gdbgui) but did not follow up on this back then. 

Before running from source I did a 
`$ python3 -m pip install -r requirements.txt`
to ensure everything is up to date. The cygwin environment is a (relatively) clean and new install.

Other info:
```
$ gdb -v
GNU gdb (GDB) (Cygwin 7.10.1-1) 7.10.1
 ... 

$ python3 gdbgui/backend.py -v
0.7.9.5

$ pip3 freeze
appdirs==1.4.3
asn1crypto==0.22.0
cffi==1.9.1
chardet==2.3.0
click==6.7
cryptography==1.8.1
enum-compat==0.0.2
eventlet==0.21.0
Flask==0.12.2
Flask-Compress==1.4.0
Flask-SocketIO==2.9.2
gdbgui==0.7.9.5
gevent==1.2.2
gevent-websocket==0.10.1
greenlet==0.4.12
idna==2.5
itsdangerous==0.24
Jinja2==2.9.6
lockfile==0.12.2
lxml==3.7.3
MarkupSafe==1.0
numpy==1.11.2
packaging==16.8
ply==3.9
pyasn1==0.2.3
pycparser==2.17
pygdbmi==0.7.4.4
Pygments==2.2.0
PyOpenGL==3.1.0
PyOpenGL-accelerate==3.1.0
pyOpenSSL==16.2.0
pyparsing==2.1.10
pypugjs==4.2.2
python-engineio==1.7.0
python-socketio==1.8.0
requests==2.13.0
six==1.11.0
urllib3==1.20
virtualenv==15.1.0
Werkzeug==0.12.2

```

**Comment by cs01** [comment]
I don't have a Windows 7 OS to test on, but I just confirmed that I can run in WIndows 10 with the following. Btw it looks like you have not upgraded your version of gdbgui (latest is 0.9.1.0 and your output shows 0.7.9.5). Upgrading may help. You may also want to try making a virtualenv with the pip dump below. If it still doesn't work, it's likely a compatibility issue between Windows 7 and Flask-SocketIO.

```
$ python3 gdbgui/backend.py -v
0.9.1.0
```

```
$pip3 freeze
appdirs==1.4.3
asn1crypto==0.22.0
cffi==1.9.1
chardet==2.3.0
click==6.7
cryptography==1.8.1
Flask==0.12.2
Flask-Compress==1.4.0
Flask-SocketIO==2.9.2
greenlet==0.4.12
idna==2.5
itsdangerous==0.24
Jinja2==2.10
lockfile==0.12.2
lxml==3.7.3
MarkupSafe==1.0
packaging==16.8
ply==3.9
pyasn1==0.2.3
pycparser==2.17
pygdbmi==0.7.4.5
Pygments==2.2.0
pyOpenSSL==16.2.0
pyparsing==2.1.10
pypugjs==4.2.2
python-engineio==2.0.1
python-socketio==1.8.3
requests==2.13.0
six==1.10.0
urllib3==1.20
Werkzeug==0.12.2
```

**Comment by aha79** [comment]
Thanks for the quick response. I had to uninstall the old gdbgui python package (0.7.9.5) before `$ python3 gdbgui/backend.py -v` was printing the version number 0.9.1.0 (which I ran on the fresh git source code). I don't know if this is intentional or not.

Unfortunately it also did not work with 0.9.1.0. 

Also creation of the virtualenv with the packages you suggested did not change anything. 

However I performed some investigations and was able to track down the problem by adding `traceback.print_exc()` in the relevant python code. What solved the problem was the following

* Install eventlet and gevent package in the virtualenv (the missing modules seemed to prevent Flask-SocketIO to load the async mode submodule)
* I manually applied the patch (found by googlingat [https://bugs.python.org/file45163/cygwin-pyio-setmode.patch](https://bugs.python.org/file45163/cygwin-pyio-setmode.patch))
```
diff -r 74eb9c51d64e Lib/_pyio.py
--- a/Lib/_pyio.py	Thu Oct 20 16:33:39 2016 -0400
+++ b/Lib/_pyio.py	Fri Oct 21 06:38:50 2016 +0900
@@ -13,8 +13,13 @@
     from _thread import allocate_lock as Lock
 except ImportError:
     from _dummy_thread import allocate_lock as Lock
-if sys.platform in {'win32', 'cygwin'}:
+if sys.platform == 'win32':
     from msvcrt import setmode as _setmode
+elif sys.platform == 'cygwin':
+    import ctypes
+    _cygwin1 = ctypes.PyDLL('cygwin1.dll')
+    def _setmode(fd, mode):
+        return _cygwin1._setmode(ctypes.c_int(fd), ctypes.c_int(mode))
 else:
     _setmode = None
```  
This fixed the exception that the module 'msvcrt' was not found during load of 'eventlet'. Then the message 'failed to initialize socketio app with async mode "eventlet". Continuing with async mode "threading".' of gdbgui disappeared.
* Finally I added the flag 'use_reloader=False' in the 'socketio.run' command on line 131 in backend.py. Thie prevented the restarting (which I do not understand, why it happend)  and premature termination of gdbgui. Then I was able to open  gdbgui in webbrowser and to debug a program :-)

**Comment by cs01** [comment]
> Then I was able to open gdbgui in webbrowser and to debug a program :-)

Nice! Hope you are liking it. I think Windows compatibility for gdbgui is a problem many people face and getting some answers here will be really helpful.

Can you do me a favor and answer some of these questions? It will help me modify the code/documentation so that gdbgui works for windows users with a little less hacking. If you have any other ideas to make this work for all users long-term here I would love to hear.

- What was the exact traceback you got when running gdbgui?
- If you run gdbgui in cygwin with python2 (and appropriate python2 dependencies installed), does it work without the patch you used?
- If you run gdbgui with python3 without the patch, but with the following change to `gdbgui/backend.py`, does it work?
    - Change 
    `socketio.server_options['async_mode'] = async_mode`
    to 
    `socketio.server_options['async_mode'] = 'threading'`
