### ISSUE TITLE
Debugging a CLI program

### ISSUE THREAD

**Issue by rellieberman** [cs01/gdbgui#142]
Is it possible to use gdbgui to debug a CLI program. I can't get a separate terminal to run for i/o, and every time my program asks for input gdb freezes .

Thanks, Great tool!

**Comment by cs01** [comment]
Thanks, great to hear you like it.

I believe #141 might resolve your problem. Until that's added, another thing you could try is the following.

- type `tty` in a terminal. It will output something like  `/dev/pts/0`
- open gdbgui in another terminal
- in gdbgui's terminal widget, type `tty /dev/pts/0`. Now all i/o is done through that terminal.

Read more: https://sourceware.org/gdb/onlinedocs/gdb/Input_002fOutput.html
