### ISSUE TITLE
gdbgui + cookie disabled : print a warning ?

### ISSUE THREAD

**Issue by d-j-a-y** [cs01/gdbgui#148]
gdbgui display a blank page in the browser when cookies are disabled.

I suggest to display a message (in the browser and gdbgui console) to warn the user about the necessity the accept at least gdbgui ip host (default 127.0.0.1)

Nota : i don't have found any information about cookies necessity into the documentation either and so open a PR : https://github.com/cs01/gdbgui/pull/147

**Comment by cs01** [comment]
Added in 0.9.2.0.
