### ISSUE TITLE
Missing dependency on pypugjs

### ISSUE THREAD

**Issue by 0ndorio** [cs01/gdbgui#151]
##### Describe the issue
It seems like pypugjs is no longer available and so gdbgui can't get installed.

> https://github.com/matannoam/pypugjs is 404
> https://pypi.python.org/pypi/pypugjs is 404

##### Steps to replicate

* `git clone https://github.com/cs01/gdbgui`
* `cd gdbgui/`
* `virtualenv venv -p python3`
* `source venv/bin/activate`

```
➤ pip install -r requirements.txt
[....]
Collecting pypugjs==4.2.2 (from -r requirements.txt (line 3))
  Could not find a version that satisfies the requirement pypugjs==4.2.2 (from -r requirements.txt (line 3)) (from versions: )
No matching distribution found for pypugjs==4.2.2 (from -r requirements.txt (line 3))
```

**Comment by cs01** [comment]
Thanks for reporting this. You're right, somehow it disappeared.

I released a new version of gdbgui (0.9.4.1) without the pypugjs dependency.

It can be installed with `pip install gdbgui --upgrade`.

Sorry for the inconvenience. That is quite surprising that `pypugjs` would disappear like that.
