### ISSUE TITLE
C++ STL Container Support

### ISSUE THREAD

**Issue by lmcapser** [cs01/gdbgui#155]
##### Describe the issue
Is there a way to view the contents of STL Containers (std::string, std::vector, std::map, etc)?

##### Steps to replicate

* Debug a program using STL Containers
* Expand a local STL Container Variable (even something simple like an std::string
* Try to find the actual value it contains (was eventually able to find an address pointer to a memory buffer and to view the memory data before I could find the string value in the GUI

##### Describe your environment
* CentOS-7 - kernels 3.10.0 and 4.4.21:
* gdbgui version 0.9.4.1:
* gdb version 7.6.1 and 7.12.1:
* browser: firefox
* python packages (`pip freeze`):
click-6.7
enum34-1.1.6
enum-compat-0.0.2
eventlet-0.21.0
Flask-0.12.2
Flask-Compress-1.4.0
Flask-SocketIO-2.9.3
gdbgui-0.9.4.1
gevent-1.2.2
greenlet-0.4.12
itsdangerous-0.24
pygdbmi-0.8.2.0
Pygments-2.2.0
pypugjs-4.2.2
python-engineio-2.0.2
python-socketio-1.8.4
six-1.11.0
Werkzeug-0.13

**Comment by cs01** [comment]
Yes, by default gdbgui turns "pretty printing" on (`-enable-pretty-printing`), but this can be turned off by unchecking **Settings > Pretty print dynamic variables (requires restart)**. You will have to kill the gdbgui server, then restart it for it to take effect.

**Comment by cs01** [comment]
Actually I think I misread your question. You can also view STL content values in gdbgui as well: ![](https://raw.githubusercontent.com/cs01/gdbgui/master/screenshots/hover.png)

![image](https://user-images.githubusercontent.com/5715368/34795987-f23180c8-f608-11e7-9743-675243a19dff.png)


The requirement is that the gdb executable you are running must have python support, which it usually does by default (`./configure --with-python` to build the gdb makefile, then build gdb). Do you know if yours does? Does it display something like I pasted in my previous comment or like one of the two images in this comment?

**Comment by lmcapser** [comment]
Maybe it's my gdb?  This is what I'm seeing:
![gdbgui_map](https://user-images.githubusercontent.com/234526/34796946-85d3f36e-f614-11e7-824e-60908da44db5.png)
![gdbgui_string](https://user-images.githubusercontent.com/234526/34796947-86234c66-f614-11e7-8d9d-29ab8ccac478.png)
![gdbgui_vector](https://user-images.githubusercontent.com/234526/34796948-863a995c-f614-11e7-93bb-e58002cdbbe9.png)

If I use the gdb command "p my_string", I see the string down in the details under _M_local_buf, but neither the popup nor the "local variables" panel will show the actual variable contents.

I'll check on both versions of gdb I'm using and see if that's the source of the problem.

Thanks,
Lance

**Comment by cs01** [comment]
Yes it appears your gdb binary was not compiled with python support.

**Comment by cs01** [comment]
I am assuming the issue here is that your version of gdb was not compiled with python support, so closing. Let me know if there is something else going on and we can reopen.

**Comment by lmcapser** [comment]
I'm still working through issues, but I have managed to get the desired
data when gdb is working.  One question, is the following normal for "maps"?

From the GDB command-line interface:

*p dict*
*$1 = std::map with 3 elements = {["One"] = 1, ["Three"] = 3, ["Two"] = 2}*


And from the gdbgui screen:


*​- dict:{...} *
*std::map<std::basic_string . . .*

*        [0]:"One" **const std::basic_string . . .*

*        [1]:1** int*

*        [2]:"Three" **const std::basic_string . . .*
*        [3]:3** int*

*        [4]:"Two" **const std::basic_string . . .*
*        [5]:2** int*


It would be great to see something closer to gdb's original layout:

*​- dict:{...} *
*std::map<std::basic_string . . .*

*        ["One" **const std::basic_string**] = **1** int*

*        ["Three" **const std::basic_string**] = **3** int*

*        ["Two" **const std::basic_string**] = **2** int*

or just:

*​- dict:{...} *
*std::map<std::basic_string . . .*

*        ["One"**] = **1*

*        ["Three"**] = **3*

*        ["Two"**] = **2*



Just a thought ;)

Thanks for the help and feedback and for all your work on a great tool!
Lance

**Comment by cs01** [comment]
That's a good suggestion. I will re-open this ticket to remind me to investigate this.

**Comment by cs01** [comment]
This is standard behavior for gdb and I do not see it as big enough need to address it, so I am closing the issue since I simply don't have the bandwidth to take it on, nor really see it as a big problem.

**Comment by superuzir** [comment]
Hello! Is **nested** STL containers visualization available?

```
gdbgui --version
0.13.1.1
```

```
gdb --version
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
```

```cpp
int main(int argc, char *argv[]){
	std::vector<float> v(7, 0.3);

	std::vector<std::vector<float>> vv(2, std::vector<float>(3, 0.4));

	std::map<int,std::vector<float>> m;
	m[1] = std::vector<float>(2, 0.5);
	m[2] = std::vector<float>(3, 0.7);
	return 0;
}
```

`{...}` things cannot be expanded


![image](https://user-images.githubusercontent.com/15436186/51169033-6c942d00-18dd-11e9-944a-2407a22dc8ad.png)

GDB CLI prints it well

![image](https://user-images.githubusercontent.com/15436186/51169240-f93eeb00-18dd-11e9-8ee4-7db58d563aba.png)

**Comment by cs01** [comment]
Yes this should definitely be viewable.  Would you mind creating a new issue so this doesn’t get lost on a closed issue?
