### ISSUE TITLE
"Remote register badly formatted" on CentOS VirtualBox running in Windows

### ISSUE THREAD

**Issue by JDang3** [cs01/gdbgui#157]
##### Describe the issue
Remote register badly formatted: T0506:0000000000000000;07:90e6ffffff7f0000;10:70c1ddf7ff7f0000;thread:p6f8.6f8;core:0;nhere: 00000000;07:90e6ffffff7f0000;10:70c1ddf7ff7f0000;thread:p6f8.6f8;core:0;

##### Steps to replicate

* Step 1.  
sudo service firewalld stop

* Step 2.  
Compile this code: gcc -std=c++11 test.cpp -o test -g
#include <cstdio>

int main()
{
    printf("hello from ConsoleApplication1!\n");
    int a = 1;
    a++;
    printf("hello 321");

    return 0;
}

* Step 3
sudo gdbserver 127.0.0.1:3000 ./test

* Step 4.
On Windows run gdbgui

*Step 5.
connect to gdbserver remote ip (taken from ifconfig) and port 3000
then error 

##### Describe your environment
* Operating system and version: CentOS Linux release 7.4.1708 (Core) - Virtual Box
* gdbgui version (`gdbgui -v`): 0.10.1.0
* gdb version (`gdb -v`): GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-100.el7
* browser: Chrome Version 63.0.3239.132 (Official Build) (64-bit)
* python packages (`pip freeze`):
astroid==1.5.3
autosub==0.3.11
backports.functools-lru-cache==1.4
chardet==2.3.0
click==6.7
colorama==0.3.9
configparser==3.5.0
enum34==1.1.6
Flask==0.12.2
Flask-Compress==1.4.0
Flask-SocketIO==2.9.3
gdbgui==0.10.1.0
gevent==1.2.2
google-api-python-client==1.5.5
greenlet==0.4.12
httplib2==0.9.2
isort==4.2.15
itsdangerous==0.24
Jinja2==2.10
lazy-object-proxy==1.3.1
MarkupSafe==1.0
mccabe==0.6.1
oauth2client==4.0.0
progressbar==2.3
pyasn1==0.1.9
pyasn1-modules==0.0.8
pygdbmi==0.8.2.0
Pygments==2.2.0
pylint==1.7.2
pysrt==1.1.1
python-engineio==2.0.2
python-socketio==1.8.4
requests==2.12.4
rsa==3.4.2
singledispatch==3.4.0.3
six==1.10.0
uritemplate==3.0.0
Werkzeug==0.14.1
wrapt==1.10.11

**Comment by cs01** [comment]
Is it possible this is a gdb issue and not a gdbgui issue? Looks like the target architecture may need to be changed to whatever is CentOS is running in the Virtual Box. See [this link](https://bugzilla.redhat.com/show_bug.cgi?id=190810).

Try running `set architecture <tab>` and see what your options are.

To see your architecture you can try `lscpu | grep Architecture`

**Comment by cs01** [comment]
Have you had a chance to try changing the architecture? I'm going to close this issue. Let me know if you're still having problems and I can reopen it.

**Comment by willmafh** [comment]
Hello...I am trying to use gdbgui on Windows to debug a program running on Centos...But encountering the same problem...How can I solve this problem...
![gdbguiproblem](https://user-images.githubusercontent.com/11711429/48542517-4f9da680-e8fa-11e8-9b16-089a06a0a522.PNG)
![gdbguipro](https://user-images.githubusercontent.com/11711429/48542522-52000080-e8fa-11e8-8cb3-ae16ea471495.PNG)
