### ISSUE TITLE
Add sourceFileMap support

### ISSUE THREAD

**Issue by RPGillespie6** [cs01/gdbgui#158]
##### Describe the issue
We build our programs in a docker environment, and so the source files in the debug symbols all have a docker filepath prefix. It would be nice to be able to provide a sourceFileMap like [VSCode allows](https://github.com/Microsoft/vscode-cpptools/blob/master/launch.md#additional-properties) to map the docker path to the real path. For example:

`./gdbgui_0.10.1.0 -g /opt/linaro/5.2.1/bin/aarch64-linux-gnu-gdb -m "/docker/buildenv":"/real/path"`

I am able to work around the issue by setting the working directory in `gdb` which then allows gdb to use relative paths instead of absolute ones.

##### Steps to replicate

* Step 1

Build binary in docker container

* Step 2

Debug binary outside of docker container

##### Describe your environment
* Operating system and version: Ubuntu 16.10
* gdbgui version (`gdbgui -v`): 0.10.1.0

**Comment by cs01** [comment]
Good suggestion. Do you think it makes more sense to put it on the command line or as an option in the settings in the front end?

**Comment by RPGillespie6** [comment]
I personally prefer CLI because then I can put all the settings I want into an alias and then call the alias. That way I don't have to fiddle with front end settings every time I want to set it up. But that's just me.
