### ISSUE TITLE
Request: shrinkable panels on left hand side

### ISSUE THREAD

**Issue by astylos** [cs01/gdbgui#162]
##### Describe the issue
Hope I've got the terminology correct but it would be great if the "panels" on left of UI (that contain each of signals, threads, local variables etc.) could be sized vertically. I'd love to shrink 'threads' so it just shows a few frames of the stack. That way I'd be able to see more of local variables, expressions etc. without scrolling.

**Comment by astylos** [comment]
Not a javascript expert, but this could be easier to implement and would allow more to be viewed: don't line-wrap in threads for func and file columns. Most cells end up spanning a couple of lines which eats a lot of screen real-estate. Guess it would need column resizing so content can be viewed if not fitting in the cell.

**Comment by cs01** [comment]
Someone else was asking about this too. I started working on adjustable components where you can click and drag to resize them. I will take both your comments into consideration, thanks!

**Comment by astylos** [comment]
Just tried this out in 0.10.3.0 and it works brilliantly.
