### ISSUE TITLE
gdbgui_0.10.2.0 - expressions stop evaluating, attempts to expand local variables fail

### ISSUE THREAD

**Issue by astylos** [cs01/gdbgui#163]
##### Describe the issue
When debugging using executable gdbgui_0.10.2.0 expressions stop evaluating when stepping through code (s or n) and attempts to expand local variables by clicking on '+' has no effect. Reverting to 0.10.1.0 resolves the issues.

##### Steps to replicate
1) Set breakpoint and run
2) enter a couple of expressions
3) step over some code
4) Try expanding local variabl;es using '+' - will fail
5) Notice that expressions are not evaluating 

##### Describe your environment
OS:
Ubuntu 17.10
* gdbgui version (`gdbgui -v`):
0.10.2.0 (executable gdbgui_0.10.2.0)
* gdb version (`gdb -v`):
GNU gdb (Ubuntu 8.0.1-0ubuntu1) 8.0.1
* browser:
Firefox 58.0

**Comment by cs01** [comment]
Interesting, thanks for reporting this. I'll look into it.

**Comment by cs01** [comment]
Dang sorry that happened. I didn't try to reproduce, but instead I pushed a new binary to gdbgui.com for v0.10.3.0. Let me know if you see the error there too. I just tested in Firefox 57 on Ubuntu 16.04 and the locals and expressions worked.

**Comment by astylos** [comment]
I'm using 0.10.3.0 resolves the issues. Appreciate the quick turnaround, and just want to say gdbgui is a great tool.

**Comment by cs01** [comment]
Thanks, I really appreciate hearing that. Spread the word!

**Comment by cs01** [comment]
Actually I just noticed this still exists in the current version, but only after certain actions. 

To reproduce, try to create an invalid expression. This puts gdbgui in a state where it can no longer create new locals or expressions. 

I will fix this in the next gdbgui version.

**Comment by astylos** [comment]
I came across this a couple more times on current version but couldn't reproduce it so was waiting until I could before raising it again. Just tried it with invalid expressions and reproduces every time.
