### ISSUE TITLE
"reload/hide disassembly" button is confusing

### ISSUE THREAD

**Issue by astylos** [cs01/gdbgui#165]
I wrote an issue describing how to reproduce the fact that source code doesn't reload after binary is rebuilt and reloaded in gdbgui. Then I thought maybe 'reload/hide disassembly ' doesn't reload the disassembly, it might reload source. Turns out it does, so it has two purposes - reloading source and hiding disassembly. Especially confusing if you're not interested in the disassembly so just don't think the button is relevant to reloading source.

edit: corrected grammar

**Comment by cs01** [comment]
Hmm yeah I can see how that's confusing. What it really does is clear the source and assembly cache in the client, which forces a refetch. What do you think of changing the button text to read `Reload File`?

**Comment by astylos** [comment]
'Reload file' sounds OK to me. 

⁣

**Comment by cs01** [comment]
This has been fixed in v0.11.1.1.
