### ISSUE TITLE
Fetch Disassembly not properly detecting gdb version

### ISSUE THREAD

**Issue by DMLou** [cs01/gdbgui#166]
##### Describe the issue
When trying to fetch disassembly by clicking the "fetch disassembly" button, nothing happens and I get the following error in the gdb console:

`data-disassemble: Mode argument must be 0, 1, 2, or 3.`

I looked at the gdbgui code a bit and I think the issue may be in the `get_disassembly_format_num` function. Perhaps it's not detecting the correct version for some reason?

I manually typed the following command in the gdb console and did get disassembly to appear, so it's a work-around, if not an ideal one:

`-data-disassemble -f /path/to/source.cpp -l 1 -n 1000 -- 4`

I'll fill in the details on my OS, gdbgui, and gdb version in the section below.

##### Steps to replicate

* Load a binary in gdbgui (I'm using `gdbgui -r` as I'm running gdbgui on a test machine)
* Click "fetch disassembly"

##### Describe your environment
* Operating system and version: CentOS7 based custom Linux distro (though it's mostly stock)
* gdbgui version (`gdbgui -v`): 0.10.3.0
* gdb version (`gdb -v`): GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-100.el7
* browser: Firefox 58.0
* python packages (`pip freeze`):
aniso8601==2.0.0
Babel==0.9.6
backports.ssl-match-hostname==3.4.0.2
blessed==1.14.2
boto==2.45.0
chardet==2.2.1
Cheetah==2.4.4
cloud-init==0.7.9
configobj==4.7.2
decorator==3.4.0
Flask==0.10.1
Flask-RESTful==0.3.6
iniparse==0.4
iotop==0.6
IPy==0.75
itsdangerous==0.23
javapackages==1.0.0
Jinja2==2.7.2
jsonpatch==1.2
jsonpointer==1.9
kitchen==1.1.1
lxml==3.2.1
Markdown==2.4.1
MarkupSafe==0.11
oauth==1.0.1
perf==0.1
Pillow==2.0.0
policycoreutils-default-encoding==0.1
prettytable==0.7.2
pyasn1==0.1.9
pycurl==7.19.0
Pygments==1.4
pygobject==3.22.0
pygpgme==0.3
pyliblzma==0.5.3
pyparsing==1.5.6
pyserial==2.6
pysigset==0.3.2
python-linux-procfs==0.4.9
python-systemd-dbus==0.1
pytz==2017.3
pyudev==0.15
pyxattr==0.5.1
PyYAML==3.10
requests==2.6.0
requests-unixsocket==0.1.5
rsa==3.4.1
schedutils==0.4
scruffington==0.3.7
seobject==0.1
sepolicy==1.1
six==1.9.0
SSSDConfig==1.15.2
urlgrabber==3.10
urllib3==1.10.2
wcwidth==0.1.7
Werkzeug==0.9.1
yum-metadata-parser==1.1.4

**Comment by cs01** [comment]
Thanks for the report! 

What I think is happening is that the regular expression that tries to parse the gdb version isn't able to parse the output of your gdb binary (`GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-100.el7`). So the regex could be changed to account for your particular case,  but I think a better solution would for me to try to run the disassembly command w/ version 4, and if it fails, suppress the error message and then just try with version 3. I will change this in the next few days.

**Comment by cs01** [comment]
This has been fixed in v0.11.1.1
