### ISSUE TITLE
ReactJS

### ISSUE THREAD

**Issue by frol** [cs01/gdbgui#17]
> * This pattern provides for a reactive environment, similar to ReactJS
> * but with no build system/JSX, but at the cost of less efficiency. I prefer a Vanilla Javascript
> * to the complexity ReactJS introduces. ReactJS may be considered if performance becomes an issue
> * since it can render more efficently.

This is the comment I found in the gdbgui.js.

*Disclaimer: I haven't run this project locally, but the screencast is flickering and I am surprised that you have chosen to reimplement React with jQuery.*

What kind of complexity does React introduce in your opinion? Have you considered UMD builds (these are just good old "classic" way of packaging a module into a single .js file with globally exposed interfaces) of ReactJS? You may also like Preact and Inferno projects (they are extremely lightweight ReactJS implementations).

**Comment by cs01** [comment]
> Disclaimer: I haven't run this project locally, but the screencast is flickering 

@frol the screencast was a gif, and didn't look like it does in practice. The colors didn't match their true colors either, plus it was a little dated so I removed it. 

> I am surprised that you have chosen to reimplement React with jQuery.

I wouldn't say I implemented React with jQuery. I implemented a data driven, reactive UI with vanilla javascript. It happens to use some jQuery selectors and whatnot, but in some cases uses vanilla javascript selectors.  I think it's a very powerful and simple pattern to adopt, and was inspired by React.

Whether or not to use React has been debated quite a bit, and will be a topic of discussion for a while. It's clear to me that node, npm, and another build system is nonzero complexity, not to mention getting a handle on React's ins-and-outs. I also don't get why I'd want to use JSX when es6 template literals are so powerful. With that being said I appreciate your suggestions and alternate approaches to React (same to you @xmo-odoo), and will check them out.

**Comment by frol** [comment]
@cs01 Thank you for your prompt response and this nice project! Good luck!

**Comment by xmo-odoo** [comment]
> I also don't get why I'd want to use JSX when es6 template literals are so powerful.

JSX is zero-cost — in the C++/Rust sense, it's compiled to creating the corresponding objects directly — and I think more clear/flexible, you can have JSX inside JS inside JSX since JSX is ultimately just compiled to JS (so you can e.g. map an array to a JSX node). ES6 templates are powerful but they have to be entirely processed at runtime and nesting templates inside templates isn't for the faint of heart.

Also note that you can use React (and friends I assume) without JSX by calling the relevant functions/constructors directly.

**Comment by cs01** [comment]
`gdbgui` has gotten large and complex enough that I am reconsidering React.
