### ISSUE TITLE
Reload source file

### ISSUE THREAD

**Issue by albertfc** [cs01/gdbgui#171]
When binary is recompiled the new binary is reloaded just rerunning (r), but source file presented is the same as before. The only method  I have found to load the new source file is refreshing the browser tab, but all changes in layout, breakpoints, etc. are lost. Is there any method to do that? 

Environment
* Operating system and version: CYGWIN_NT-6.3 lenovo-albert 2.9.0(0.318/5/3) 2017-09-12 10:18 x86_64 Cygwin
* gdbgui version (`gdbgui -v`): 0.11.0.0
* gdb version (`gdb -v`): GNU gdb (GDB) (Cygwin 7.11.1-2) 7.11.1
* browser: Google Chrome 63.0.3239.132 (Build oficial) (64 bits)
* python packages (`pip freeze`): https://pastebin.com/rLiKwhhh

**Comment by astylos** [comment]
See issue #165

**Comment by albertfc** [comment]
Thanks!
