### ISSUE TITLE
Suggestion: Deleting breakpoint from breakpoints pane should not change view in code panel

### ISSUE THREAD

**Issue by astylos** [cs01/gdbgui#172]
##### Describe the issue
Deleting a breakpoint from the breakpoints pane takes you to that location in the code panel. In my mind that is disruptive since I don't really care about debugging that code any more, so seems pointless to jump back to it. Deleting a breakpoint shouldn't change the view in the code window. Or at least, should be a configurable option. 

##### Steps to replicate
Set a breakpoint in file x.cpp
Load file y.cpp so you're viewing it in the code panel
In breakpoints panel delete the breakpoint in x.cpp
x.cpp gets loaded in code panel, at point where deleted breakpoint existed

##### Describe your environment
Ubuntu 17.10, gdbgui 0.11.0.0 executable, gdb 8.0.1

**Comment by cs01** [comment]
Agreed, I'll change in the next release

**Comment by cs01** [comment]
this has been fixed in v0.11.1.1
