### ISSUE TITLE
Inferior fails to launch on openSUSE Leap 42.2 due to libtinfo not providing _nc_outch_sp

### ISSUE THREAD

**Issue by ebaudrez** [cs01/gdbgui#181]
##### Describe the issue

On openSUSE Leap 42.2, the inferior debugger fails to launch. The symptom is the following (in the console pane of the gdbgui GUI):

    gdbgui spawned subprocess with pid 21941 from executable gdb.
    gdb process 21941 is running for this tab
    The underlying gdb process has been killed. This tab will no longer function as expected.

This happens every time gdbgui is launched, regardless of arguments.

##### Steps to replicate

* Launch gdbgui on the command line.
* Navigate to 127.0.0.1:5000
* The message(s) appear(s) immediately in the console pane. No debugging is possible.

##### Describe your environment
* Distribution: openSUSE Leap 42.2, 
* `uname -a`: `Linux <hostname> 4.4.104-18.44-default #1 SMP Thu Jan 4 08:07:55 UTC 2018 (05a9de6) x86_64 x86_64 x86_64 GNU/Linux`
* gdbgui version (`gdbgui -v`): 0.11.1.2
* gdb version (`gdb -v`): 8.0.1
* browser: tested in Firefox 52.6.0 and Chrome Version 65.0.3325.146 (Official Build). The problem is likely not related to the browser.
* python packages (`pip freeze`): N/A as I'm using the standalone binary.

##### Investigation

`strace`ing the binary reveals the following information. These are the relevant excerpts from the forked process that `exec`s the debugger:

    execve("/usr/bin/gdb", ["/usr/bin/gdb", "--interpreter=mi2"], [<environment info stripped .......>]
    open("/tmp/_MEImWZSco/libncursesw.so.5", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    open("/lib64/libncursesw.so.5", O_RDONLY|O_CLOEXEC) = 3
    open("/tmp/_MEImWZSco/libtinfo.so.5", O_RDONLY|O_CLOEXEC) = 3
    writev(2, [{"/usr/bin/gdb", 12}, {": ", 2}, {"symbol lookup error", 19}, {": ", 2}, {"/lib64/libncursesw.so.5", 23}, {": ", 2}, {"undefined symbol: _nc_outch_sp", 30}, {"", 0}, {"", 0}, {"\n", 1}], 10) = 91
    exit_group(127)                         = ?

(I have stripped much for legibility, but I have the full logs available.) Note how it uses the `libncursesw` library from my system, but the `libtinfo` shipped with gdbgui. However, my system `libncursesw` requires the following symbol:

    $ eu-readelf -s /lib64/libncursesw.so.5
    Symbol table [ 4] '.dynsym' contains 661 entries:
     1 local symbol  String table: [ 5] '.dynstr'
      Num:            Value   Size Type    Bind   Vis          Ndx Name
       37: 0000000000000000      0 FUNC    GLOBAL DEFAULT    UNDEF _nc_outch_sp

It is provided by my system's `libtinfo` library:

    $ eu-readelf -s /lib64/libtinfo.so.5
    Symbol table [ 4] '.dynsym' contains 315 entries:
     1 local symbol  String table: [ 5] '.dynstr'
      Num:            Value   Size Type    Bind   Vis          Ndx Name
      206: 000000000001aaf0    187 FUNC    GLOBAL DEFAULT       13 _nc_outch_sp

but not by the one shipped with `gdbgui`, i.e.,

    $ eu-readelf -s /tmp/_MEIQ2ccQj/libtinfo.so.5  | grep _nc_outch_sp

returns nothing.

    $ rpm -qf /lib64/libncursesw.so.5 /lib64/libtinfo.so.5
    libncurses5-5.9-55.9.1.x86_64
    libncurses5-5.9-55.9.1.x86_64

I wasn't able to figure out the version of ncurses that was shipped with gdbgui.

**Comment by cs01** [comment]
Great investigation. I see three ways to fix the issue. The binary is built with pyinstaller, a third party python library. pyinstaller builds binaries only for the platform on which you are building on (no cross compiling). I think it uses various libraries it finds on the system it's building on and bundles them up into an executable. It then extracts them into a tmp directory starting with `_MEI`. So what you're seeing looks like .so's from the system gdbgui was built on (ubuntu). 

Therefore the first option is to rebuild the executable with pyinstaller on openSUSE so the right .so gets bundled in the executable. The second would be to modify pyinstaller to bundle multiple shared objects for better platform support, or shared objects with more symbols. The third (and probably the one that makes the most sense for you) is to just use the python package or run from source.

**Comment by ebaudrez** [comment]
Hi Chad, thanks for your quick reply. Fair enough, the download page did say "Ubuntu 14.04+". `pip install --user gdbgui --upgrade` worked fine on my platform. This solves my immediate problem, so as far as I'm concerned, this issue can be closed.

I'm not knowledgeable about Python or its ecosystem, so I'm afraid I cannot help you with packaging gdbgui for openSUSE. However, I wonder if Docker would not be an option? I'll see if I can find the time to create a Docker image ...
