### ISSUE TITLE
show number of times breakpoint was hit (use`times` field on breakpoint)

### ISSUE THREAD

**Issue by cs01** [cs01/gdbgui#187]
Add a field on the breakpoint that shows the number of times a breakpoint was hit. See [The -break-list Command](https://www.sourceware.org/gdb/onlinedocs/gdb/GDB_002fMI-Breakpoint-Commands.html#GDB_002fMI-Breakpoint-Commands).

**Comment by cr7-ankit** [comment]
Is this issue still open? I am a beginner and new to open Source and looking forward to contributing. It would be a great help if any of you senior can guide me and make me successful in my very first contribution I am willing to do.
Thanks
