### ISSUE TITLE
--args does not function as expected

### ISSUE THREAD

**Issue by fritzr** [cs01/gdbgui#194]
##### Description
When running `gdbgui --args ....` one would expect to be able to paste the program arguments following the `--args` option, as with gdb. However it appears that gdbgui attempts to interpret options following `--args` as options to gdbgui itself instead of the inferior to debug, contrary to the text in `gdbgui --help`.

##### Steps to replicate

```bash
$ gdbgui --args `which gcc` -c test.c -o test.o
usage: gdbgui [-h] [--args ARGS [ARGS ...]] [-x GDB_CMD_FILE] [-g GDB] [--rr]
              [-p PORT] [--host HOST] [-r] [--auth-file AUTH_FILE]
              [--user USER] [--password PASSWORD] [--key KEY] [--cert CERT]
              [--license LICENSE] [--project PROJECT] [-v]
              [--hide_gdbgui_upgrades] [-n] [--debug]
              [cmd [cmd ...]]
gdbgui: error: unrecognized arguments: -c -o test.o
```

##### Environment
* Operating system and version: Linux 2.6.32-696.23.1.el6.centos.plus.x86_64 x86_64 GNU/Linux
* gdbgui version (`gdbgui -v`): 0.11.3.1
* gdb version (`gdb -v`): GNU gdb (GDB) 7.8.1
* browser: Firefox 52.7.0
* python packages (`pip freeze`):
```
backports-abc==0.5
backports.shutil-get-terminal-size==1.0.0
backports.ssl-match-hostname==3.5.0.1
certifi==2017.11.5
click==6.7
decorator==4.1.2
enum34==1.1.6
Flask==0.12.4
Flask-Compress==1.4.0
Flask-SocketIO==3.0.0
funcsigs==1.0.2
gdbgui==0.11.3.1
gevent==1.3.1
greenlet==0.4.13
ipykernel==4.6.1
ipython==5.0.0
ipython-genutils==0.2.0
itsdangerous==0.24
Jinja2==2.10
jupyter-client==5.1.0
jupyter-core==4.4.0
lxml==4.2.1
manhole==1.5.0
MarkupSafe==1.0
mock==2.0.0
numpy==1.11.1
pathlib2==2.3.0
pbr==1.10.0
pdb-clone==1.10
pexpect==4.3.0
pickleshare==0.7.4
prompt-toolkit==1.0.15
protobuf==3.0.0b2
ptyprocess==0.5.2
pygdbmi==0.8.2.0
Pygments==2.2.0
python-dateutil==2.6.1
python-engineio==2.1.1
python-socketio==1.9.0
pyzmq==16.0.3
scandir==1.6
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.10.0
tornado==4.5.2
traitlets==4.3.2
wcwidth==0.1.7
Werkzeug==0.14.1
```

**Comment by fritzr** [comment]
It looks like `gdbgui --args "args ..."` (with auotes around the full program arguments) does work. However, this is not how the help explains it:

```
usage: gdbgui [-h] [--args ARGS [ARGS ...]] [-x GDB_CMD_FILE] [-g GDB] [--rr]
              [-p PORT] [--host HOST] [-r] [--auth-file AUTH_FILE]
              [--user USER] [--password PASSWORD] [--key KEY] [--cert CERT]
              [--license LICENSE] [--project PROJECT] [-v]
              [--hide_gdbgui_upgrades] [-n] [--debug]
              [cmd [cmd ...]]
```

Recommend updating the usage string to show quotes around the entire program string with arguments for clarity.

**Comment by fritzr** [comment]
It looks like `gdbgui --args "cmd args..."` (with quotes around the full program string, including flags and arguments) does work. However, this is not how it is described in the usage string:

```
usage: gdbgui [-h] [--args ARGS [ARGS ...]] [-x GDB_CMD_FILE] [-g GDB] [--rr]
              [-p PORT] [--host HOST] [-r] [--auth-file AUTH_FILE]
              [--user USER] [--password PASSWORD] [--key KEY] [--cert CERT]
              [--license LICENSE] [--project PROJECT] [-v]
              [--hide_gdbgui_upgrades] [-n] [--debug]
              [cmd [cmd ...]]
```

Recommend updating the usage text to show quotes around `--args "ARGS..."`.

**Comment by cs01** [comment]
Good stuff, thanks! Apologies for the inconvenience. PRs welcome if you feel up to it.

**Comment by fritzr** [comment]
PR #198 submitted
