### ISSUE TITLE
The "r" key should toogle the reverse checkbox when used with rr.

### ISSUE THREAD

**Issue by nbp** [cs01/gdbgui#201]
##### Describe the issue
description here

##### Steps to replicate

$ rr record …
$ gdbgui --rr -r

Within Firefox, type:
> c       #  stop at the SEGV.
> b …  #  add a breakpoint
> rc      # Restart and continue instead of doing a reverse-continue.

The problem is that "r" is interpreted as the "run" command, while it should probably be a toggle for the "reverse" checkbox when --rr is used on the command line.

##### Describe your environment
* Operating system and version: NixOS
* gdbgui version (`gdbgui -v`): 0.11.1.2
* gdb version (`gdb -v`): 8.1
* rr version (`gdb -v`): 5.1.0
* browser: Firefox nightly
* python packages (`pip freeze`): command not found. (installed with Nix)

**Comment by cs01** [comment]
This is just my intuition, but I think `r` will be used more often for run rather than reverse since I *think* reverse debugging is fairly rare. What if instead holding down the shift key (or just using a capital letter) sent the equivalent command in reverse?

**Comment by nbp** [comment]
I meant when `--rr` is used, there is no need for restart and the `r` key can then be used for reverse.
