### ISSUE TITLE
start gdb with --nx command line option (do not read any .gdbinit files in any directory)

### ISSUE THREAD

**Issue by ZungBang** [cs01/gdbgui#205]
At work we use a company wide gdbinit file that provides pretty-printers for some common types (both in-house types and c++ std types) - it seems to be buggy, so in some cases it causes gdb to hang when responding to `1-stack-list-variables --simple-values`, which causes gdbgui to hang in turn.

I suggest to start gdb with `--nx` either always or conditioned on some command line option (e.g. `--nx` or `--safe-mode`). I hard-coded it at my end into `statemanager.py` when creating `GdbController` and it does the trick ...

**Comment by cs01** [comment]
`gdbgui` used to run with `--nx`, but somebody requested it be removed so they could use their .gdbinit files 😆
