### ISSUE TITLE
Syntax highlighting for debugged source?

### ISSUE THREAD

**Issue by sztomi** [cs01/gdbgui#21]
I suppose [highlightjs](https://highlightjs.org/) would be reasonably easy to integrate into this project and would be very beneficial to the user experience.

**Comment by cs01** [comment]
I thought about using that, but in the end I think I'm going to do it on the server side in Python with `pygments`. I agree it would help to add syntax highlighting, it's a little hard to read black on white.

**Comment by cs01** [comment]
Here is requirements for a highlighter, let me know if you think highlightjs can do it, and I may end up using it.

* Able to provide marked up source code with syntax tags in an array, with each element of the array corresponding to a line of code, such as

```
["<span class='keyword'>#define</span> <span class='variable'>MYVAR</span> <span class='value'>5</value>",
"<span class='keyword'>#define</span> <span class='variable'>MYOTHERVAR</span> <span class='value'>10</value>"]
```

* Able to use various color schemes

**Comment by sztomi** [comment]
Highlighjs is client side, so if you meant this on the server side, then pygments is a better choice. Otherwise, highlightjs does create DOM elements as per its lexer on the client side.

**Comment by cs01** [comment]
It doesn't **need** to be server-side, that was just what I was going to go with. In my requirements, I didn't specify server-side. Does highlightjs meet these requirements? I need to be able to get just the source code in an array, because gdbgui needs to add clickable line numbers, and inline disassembly.

**Comment by sztomi** [comment]
You get a DOM, which you can flatten into an array in js client side I suppose. Take a look at the hightlightjs demos: https://highlightjs.org/static/demo/ 
If you use the inspector in your browser, you can explore the generated DOM.

**Comment by cs01** [comment]
it's getting there

https://twitter.com/grassfedcode/status/839909748287782912

![image](https://cloud.githubusercontent.com/assets/5715368/23770709/040ec8be-04c9-11e7-807b-11b5c52f00c5.png)

**Comment by sztomi** [comment]
Looks pretty cool!

**Comment by GitMensch** [comment]
There's only one thing left to the highlighter: adjustable file types (or documentation how to do so)
I have some file extensions that the highlighter _could_ highlight correctly but it goes back to the file name extension (at least I guess so).

Can we have an output of the current used highlighter with the option to adjust this?
I guess at least for the files that actually _do_ have a file extension I could manually adjust the list "somewhere" - any pointers on this?

**Comment by sztomi** [comment]
> I have some file extensions that the highlighter could highlight correctly but it goes back to the file name extension (at least I guess so).

Sorry I couldn't parse this sentence, mind rewording a bit?

**Comment by GitMensch** [comment]
An example is possibly best:

change a header file to be named "myheader.yeah" and `#include "myheader.yeah"` - it will be compiled fine but when shown in the debugger it will have no highlighting.
It would be nice to be able to define "highlight all .yeah as C" and also nice to be able to temporarily override the chosen language in the UI.

**Comment by sztomi** [comment]
Oh I see. There is a python module called [guesslang](https://guesslang.readthedocs.io/en/latest/) that uses heuristics to identify languages. Maybe it's better to provide a checkbox that enables this, rather than relying on the user to set up associations?

**Comment by GitMensch** [comment]
Sounds good - best would possibly be a dropdown with all supported types showing the type that is currently used, allowing to override it, or to use the special entry "guesslang" (it would also be fine without it, so the user can manually override it)
