### ISSUE TITLE
Cannot create breakpoint: -break-insert: Garbage following <location>

### ISSUE THREAD

**Issue by GabrielMajeri** [cs01/gdbgui#211]
**Describe the bug**
I've tried to use `gdbgui` to debug a simple Rust program. Adding a breakpoint through the GUI leads to the `-break-insert: Garbage following <location>` error message.

I've searched the internet and apparently this was related to spaces in the project's path. Moving the executable and source code to a new path, with no spaces, fixes the issue.

**To Reproduce**
1. Create a new Rust project, _with spaces in the directory path_
2. Run `gdbgui target/debug/<project name>`
3. Notice that trying to add a breakpoint through the GUI does _not_ work

**Expected behavior**
`gdbgui` should work with paths with spaces in its names. If this is a limitation of GDB, then it should at least warn the user.

**Please complete the following information:**
* OS: Arch Linux x86_64
* gdbgui version: 0.12.0.0
* gdb version: 8.1
* browser [e.g. chrome, safari]: latest stable Chromium
* python packages (`pip freeze`):
```
click==6.7
Flask==0.12.4
Flask-Compress==1.4.0
Flask-SocketIO==2.9.6
gdbgui==0.12.0.0
gevent==1.3.4
greenlet==0.4.13
itsdangerous==0.24
pygdbmi==0.8.3.0
python-engineio==2.2.0
python-socketio==2.0.0
Werkzeug==0.14.1
```

**Comment by cs01** [comment]
Thanks for filing, working on a fix now.
