### ISSUE TITLE
debug session quit ⇒ gdbgui is confused

### ISSUE THREAD

**Issue by krux02** [cs01/gdbgui#214]
**Describe the bug**

I wanted to test my gdb pretty printers in gdbgui again. But I forgot to to load them before I inspected some variables. So some of the variables were expanded. Then I loaded the python script with "source nim-gdb.py". Then the mess started happening. Just see in the log below.

I was not able to restart gdb from gdbgui.

**Expected behavior**

There is no problem that things might go wrong. But there should bo a way to recover from it. For example a simple way to just restart the debugger.

**Please complete the following information:**
* OS: Arch Linux
* gdbgui version:0.12.0.0
* gdb version: GNU gdb (GDB) 8.1
* browser: chromium
* python packages: None

**Additional context**

This is the entire log that happened when loaded my python scripts 
 
```

(gdb) source nim-gdb.py

Loading Nim Runtime support.

NimEnumPrinter: lookup global symbol 'NTI_29cbg2fC1z5iM1PAI28kR5w_ failed for tyEnum_TMsgKind_29cbg2fC1z5iM1PAI28kR5w.

c-varobj.c:522: internal-error: std::__cxx11::string c_value_of_variable(const varobj*, varobj_display_formats): Assertion `varobj_value_is_changeable_p (var)' failed.
A problem internal to GDB has been detected,
further debugging may prove unreliable.
Quit this debugging session? 

(y or n) [answered Y; input not from terminal]


This is a bug, please report it.

  For instructions, see:
<http://www.gnu.org/software/gdb/bugs/>.




c-varobj.c:522: internal-error: std::__cxx11::string c_value_of_variable(const varobj*, varobj_display_formats): Assertion `varobj_value_is_changeable_p (var)' failed.
A problem internal to GDB has been detected,
further debugging may prove unreliable.
Create a core file of GDB? 

(y or n) [answered Y; input not from terminal]

The underlying gdb process has been killed. This tab will no longer function as expected.

Error occurred on server when running gdb command: gdb is not running

Error occurred on server when running gdb command: gdb is not running

No gdb response received after 10 seconds.

Possible reasons include:

1) gdbgui, gdb, or the debugged process is not running.

2) gdb or the inferior process is busy running and needs to be interrupted (press the pause button up top).

3) Something is just taking a long time to finish and respond back to this browser window, in which case you can just keep waiting.

Error occurred on server when running gdb command: gdb is not running

No gdb response received after 10 seconds.

Possible reasons include:

1) gdbgui, gdb, or the debugged process is not running.

2) gdb or the inferior process is busy running and needs to be interrupted (press the pause button up top).

3) Something is just taking a long time to finish and respond back to this browser window, in which case you can just keep waiting.

```

**Comment by cs01** [comment]
If the underlying gdb process dies you can either refresh the window, or go to the dashboard and click `open tab with new gdb process`. 

I suppose a button could be added to re-spawn a gdb process for the current window, but refreshing accomplishes the same thing, and doesn't require a bunch of cleanup to be done by gdbgui, which might end up being buggy. So I will just recommend refreshing or using the dashboard.
