### ISSUE TITLE
empty frame causes the ui to crash/black screen

### ISSUE THREAD

**Issue by shi-yan** [cs01/gdbgui#216]
**Describe the bug**
The web ui would turn to black screen from time to time. if I check the chrome developer console, I saw the following:

TypeError: Cannot read property 'addr' of undefined
    at t.value (Threads.jsx:70)
    at Sa (react-dom.production.min.js:166)
    at Na (react-dom.production.min.js:179)
    at ui (react-dom.production.min.js:201)
    at ci (react-dom.production.min.js:202)
    at Hi (react-dom.production.min.js:211)
    at Vi (react-dom.production.min.js:210)
    at Bi (react-dom.production.min.js:210)
    at Fi (react-dom.production.min.js:208)
    at pi (react-dom.production.min.js:206)

or 

TypeError: Cannot read property 'addr' of undefined
    at Function.value (Threads.jsx:99)
    at t.value (Threads.jsx:60)
    at Sa (react-dom.production.min.js:166)
    at Na (react-dom.production.min.js:179)
    at ui (react-dom.production.min.js:201)
    at ci (react-dom.production.min.js:202)
    at Hi (react-dom.production.min.js:211)
    at Vi (react-dom.production.min.js:210)
    at Bi (react-dom.production.min.js:210)
    at Fi (react-dom.production.min.js:208)

the relevant code doesn't seem to expect thread.frame is empty:

      try {
        row_data = Threads.get_row_data_for_stack(
          stack,
          this.state.selected_frame_num,
          **thread.frame.addr,**
          thread.id,
          is_current_thread_being_rendered
        );
      } catch (err) {
        row_data = ['unknown', 'unknown', 'unknown'];
        console.log(err);
      }

        **if (frame.addr === cur_frame.addr) {**
          return stack_data;
        }

**To Reproduce**

unfortunately I found this while debugging some internal code. I can't share the code.
But this problem happens quite often

**Expected behavior**

the ui shouldn't turn to a black (dark gray) screen, when that happens, the only way to get of this situation is refreshing the browser. but doing so will not reconnect to the previous debug session. the basically, I have to redebug everything, which is a pain. 

**Screenshots**

**Please complete the following information:**
* OS: host machine, x86 ubuntu 17.10, target machine, arm aarch64 ubuntu 16.04
* gdbgui version (`gdbgui -v`): 0.12.0.0
* gdb version (`gdb -v`):
GNU gdb (Ubuntu 7.11-0ubuntu1) 7.11
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "aarch64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".

* browser [e.g. chrome, safari]:
chrome

* python packages (`pip freeze`):

adium-theme-ubuntu==0.3.4
click==6.7
Flask==0.12.4
Flask-Compress==1.4.0
Flask-SocketIO==2.9.6
gdbgui==0.12.0.0
gevent==1.3.4
gps==3.15
greenlet==0.4.13
itsdangerous==0.24
Jinja2==2.10
MarkupSafe==1.0
pygdbmi==0.8.3.0
Pygments==2.2.0
pygobject==3.20.0
python-engineio==2.2.0
python-socketio==2.0.0
six==1.11.0
unity-lens-photos==1.0
Werkzeug==0.14.1

**Additional context**

**Comment by cs01** [comment]
Thanks for filing, will fix this.
