### ISSUE TITLE
firefox can't scroll down the gdb terminal view automatically

### ISSUE THREAD

**Issue by shi-yan** [cs01/gdbgui#217]
**Describe the bug**
with chrome, the gdb terminal can scroll down automatically as new lines are received. but with firefox, this doesn't work. this seems to be a bug of firefox.
the way the current ui shows the terminal seems to be appending <p></p> to the terminal panel. This is not efficient. 

a suggested fix is using https://xtermjs.org to replace the current approach. xtermjs is fast as it doesn't update the dom tree to append new lines. and I didn't seem to see problems with scrolling using firefox. or did I? I can't be sure, I will double check.

**To Reproduce**

use gdbgui with firefox

**Expected behavior**

the scroll bar of the terminal output should scroll to the bottom as new lines are available.

**Screenshots**

**Please complete the following information:**
* OS: ubuntu 17.10
* gdbgui version (`gdbgui -v`): 0.12
* gdb version (`gdb -v`): 7.0
* browser [e.g. chrome, safari]: firefox
* python packages (`pip freeze`):

**Additional context**

**Comment by cs01** [comment]
I agree that something like xterm would be really nice to use in gdbgui. Unfortunately that is a fairly large undertaking and I don't have the time to spend on it right now. I do appreciate the suggestion.

I was not able to reproduce the issue you are referring to in Firefox v60.0.1, so I'm going to close.
