### ISSUE TITLE
file tree should not add leading `/` on windows

### ISSUE THREAD

**Issue by cs01** [cs01/gdbgui#219]
Have gotten reports that eading `/` are added which causes file to not be found. Look into why whether it's doing this, and if it is, identify and fix the root cause.

I do not use Windows so this would be a great issue for the community to help with. I can answer questions about development if necessary.

**Comment by wesleyParriott** [comment]
I'm not seeing this happening. I can files just fine on my Windows 7 machine. What I am doing is placing the file path in the input box next to the "Load Binary" button. So putting something like "C:/grp/build/grp.exe" works just fine.
