### ISSUE TITLE
avoid installing inside .platformio tree

### ISSUE THREAD

**Issue by AndreaBorgia-Abo** [cs01/gdbgui#221]
Using Platform.io (PIO) & VScode, I'm a beginner wrt embedded systems.
Since the downloadable version of gdbgui is 0.12, I tried upgrading to 0.13 using the "pip" command as suggested.
Unfortunately, it used the "pip" from within PIO, which stopped working, requiring a clean reinstall.
I'm not sure there is anything you can do about it, it's more like a note to self and a warning to others :)

**Comment by cs01** [comment]
Thanks for posting. I'll update the message to not be so specific to pip. 

> I'm not sure there is anything you can do about it, it's more like a note to self and a warning to others :)

Agreed, not sure how much I can do about pip working perfectly on all computers running gdbgui.

**Comment by AndreaBorgia-Abo** [comment]
Insert obligatory xkcd reference: https://xkcd.com/1987/
I guess a reminder to run "which pip" should be enough :)
I'll try to limit the PATH with PIO's pip to PIO itself, that should prevent further issues.
Feel free to close when it is ok for you.
