### ISSUE TITLE
gdbgui command not found. 

### ISSUE THREAD

**Issue by jiesince1998** [cs01/gdbgui#224]
I successly installed gdbgui by using the command "pip install gdbgui", but when I launch gdbgui in terminal, it shows "gdbgui command not found". WHY?
![_20180812001927](https://user-images.githubusercontent.com/24897529/43993782-824a5310-9dc5-11e8-9650-519029e2d5f2.png)

**Comment by cs01** [comment]
Are you able to install other packages with pip? Looks like it was successfully installed but is not on your $PATH. You can try to add it to your $PATH env variable by modifying your .bashrc file (or whatever shell you use).

There are some other options too. 
1.) download from gdbgui.com
2.) Install with pipsi instead of pip.
```
curl https://raw.githubusercontent.com/mitsuhiko/pipsi/master/get-pipsi.py | python
```
open a new terminal
```
pipsi install gdbgui
```

now you should be able to run `gdbgui`

**Comment by jiesince1998** [comment]
Sorry, I'm a linux beginer, Can you tell me how to add it to my $PATH env variable? I can't find where gdbgui installed to.  The other options do not work either. 
![_201807280046fdfdfd09](https://user-images.githubusercontent.com/24897529/43997697-ae60adb4-9e15-11e8-8061-211294d086ab.png)
![_20180728004609_3434](https://user-images.githubusercontent.com/24897529/43997700-b32b1992-9e15-11e8-909c-da46c098ea23.png)

**Comment by jiesince1998** [comment]
I find this. 
![_20180812100930](https://user-images.githubusercontent.com/24897529/43997773-de1703f8-9e17-11e8-82e0-0f7a1b31743c.png)

**Comment by cs01** [comment]
It looks like you installed `virtualenv` and then ran `pipsi install gdbgui`, but `pipsi` was not installed yet.

Try 
```
curl https://raw.githubusercontent.com/mitsuhiko/pipsi/master/get-pipsi.py | python
```
again then open a new terminal and run
```
pipsi install gdbgui
```

If you still get an error about missing `virtualenv`, try running `pip install virtualenv` or `sudo pip install virtualenv`. Then install `pipsi`, then use `pipsi` to install gdbgui.

You can modify the PATH environment variable by modifying the file ~/.bashrc. See this link for more https://stackoverflow.com/questions/13631173/adding-a-path-to-the-bashrc-file, and use google.

Another solution would be to download the binary [here](https://gdbgui.com/downloads/linux/gdbgui_0.13.0.0), then run `chmod +x <file>`, then run it directly.

**Comment by jiesince1998** [comment]
Thank you very much for your great help. I add the PATH environment variable, and it does works. Gdbgui is powerful and beautiful!
