### ISSUE TITLE
ReferenceError: invalid assignment left-hand side in Firefox

### ISSUE THREAD

**Issue by nical** [cs01/gdbgui#23]
I am getting the error:

```
ReferenceError: invalid assignment left-hand side
```

when trying gdbgui in Firefox (Seems to work in Chromium) on Fedora.

The error happens at ```gdbgui.js:2492:8```

The code in question looks like:

```js
    set_threads: function(threads){
        State.get('threads') = $.extend(true, [], threads)
        Threads.render()
    },
```
where the assignment happens.

I tried on Firefox stable and nightly.

**Comment by cs01** [comment]
Thanks, strange that this was not occurring for me in Chrome, but was indeed an error in Firefox. Fixed in 0.7.4.1.
