### ISSUE TITLE
TypeError: register() takes from 2 to 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by mb720** [cs01/gdbgui#230]
**Describe the bug**
Calling gdbgui using `/home/me/.local/bin/gdbgui` produces this stacktrace instead of starting:

```
Opening gdbgui with default browser at http://127.0.0.1:5000
Traceback (most recent call last):
  File "/home/me/.local/bin/gdbgui", line 11, in <module>
    sys.exit(main())
  File "/home/me/.local/lib/python3.7/site-packages/gdbgui/backend.py", line 986, in main
    certificate=args.cert,
  File "/home/me/.local/lib/python3.7/site-packages/gdbgui/backend.py", line 243, in setup_backend
    b.open(url_with_prefix)
  File "/usr/lib/python3.7/webbrowser.py", line 75, in open
    register_standard_browsers()
  File "/usr/lib/python3.7/webbrowser.py", line 567, in register_standard_browsers
    cmd = _synthesize(cmdline, -1)
  File "/usr/lib/python3.7/webbrowser.py", line 116, in _synthesize
    register(browser, None, controller, update_tryorder)
TypeError: register() takes from 2 to 3 positional arguments but 4 were given
```

**To Reproduce**
1. Install gdbgui with `pip install --user gdbgui --upgrade`
2. Call `/home/me/.local/bin/gdbgui`
3. See the stacktrace

**Expected behavior**
I'd expect gdbgui to start a server at http://127.0.0.1:5000

**Please complete the following information:**
* OS: Arch Linux 4.18.1. Window manager: sway 0.15.2
* gdbgui version (`gdbgui -v`): 0.13.0.0
* gdb version (`gdb -v`): 8.1.1
* browser [e.g. chrome, safari]: Mozilla Firefox 61.0.2
* python packages (`pip freeze`):

      appdirs==1.4.3
      btrfsutil==1.0.0
      CacheControl==0.12.5
      chardet==3.0.4
      click==6.7
      colorama==0.3.9
      cupshelpers==1.0
      distlib==0.2.7
      distro==1.3.0
      docopt==0.6.2
      Flask==0.12.4
      Flask-Compress==1.4.0
      Flask-SocketIO==2.9.6
      gdbgui==0.13.0.0
      gevent==1.3.6
      greenlet==0.4.14
      html5lib==1.0.1
      idna==2.7
      itsdangerous==0.24
      Jinja2==2.10
      keyutils==0.5
      lensfun==0.3.2
      lockfile==0.12.2
      louis==3.6.0
      MarkupSafe==1.0
      msgpack==0.5.6
      packaging==17.1
      progress==1.4
      pycairo==1.17.0
      pycups==1.9.73
      pycurl==7.43.0.2
      pygdbmi==0.8.3.0
      Pygments==2.2.0
      pygobject==3.28.3
      pyparsing==2.2.0
      python-engineio==2.2.0
      python-socketio==2.0.0
      pytoml==0.1.16
      PyYAML==3.13
      requests==2.19.1
      retrying==1.3.3
      six==1.11.0
      team==1.0
      trash-cli==0.17.1.14
      udiskie==1.7.5
      urllib3==1.23
      webencodings==0.5.1
      Werkzeug==0.14.1
      youtube-dl==2018.8.4

**Additional context**
Thanks for gdbgui! :-)

**Comment by cs01** [comment]
I wonder if this is a python 3.7 api change.  I will check it out when I’m at my computer again.

**Comment by cs01** [comment]
Thanks @mb720 for reporting this and @hrantzsch for the link.

This as the link says, this is surprisingly a bug in Python itself. You should update your version of python if possible. If not, a workaround is to pass the `-n` flag to gdbgui so it avoids calling that line of code that's failing. i.e. 
```
gdbgui -n
```

**Comment by pythonnelson** [comment]
TypeError: register() takes from 2 to 3 positional arguments but 4 were given.

please someone help me out with this error. i am trying to register an app in django admin site with this code below>>>>>
------------------------------------------------------------------------------------------------------------------
**from django.contrib import admin
from .models import Computer, Printer, Wireless_Connection

admin.site.register(Computer, Printer, Wireless_Connection)**

-----------------------------------------------------------------------------------------------------------------

And these are class files that i am trying to register in the admin site/panel

### _class Computer(models.Model):
	staff_or_office = models.CharField(max_length=30)
	location = models.CharField(max_length=30)
	pc_model = models.CharField(max_length=20)
	IP_Address = models.CharField(max_length=30)
	MAC_Address = models.CharField(max_length=30)
	serial_number = models.CharField(max_length=30, default='None')
	ups = models.CharField(max_length=3, default='No')
	condition = models.CharField(max_length=10, default='Working')
	network_connection = models.CharField(max_length=30, default='None')
	no_of_network_field = models.CharField(max_length=10, default='None')

class Printer(models.Model):
    staff_or_office = models.CharField(max_length=30)
    location = models.CharField(max_length=30)
    printer_or_copier_model = models.CharField(max_length=30)
    serial_number = models.CharField(max_length=40)
    shared = models.CharField(max_length=3)
    condition = models.CharField(max_length=10)
    toner = models.CharField(max_length=30)

class Wireless_Connection(models.Model):
    staff_or_office = models.CharField(max_length=30)
    location = models.CharField(max_length=30)
    connection_model = models.CharField(max_length=30)
    serial_number = models.CharField(max_length=40)
    condition = models.CharField(max_length=10)  
 
    def __unicode__(self):
       return self.computer_name_

--------------------------------------------------------------------------------------------------------------

Please someone you inbox me if you have an idea.
**nsbkargbo@njala.edu.sl**
