### ISSUE TITLE
License to permit use in commercial settings

### ISSUE THREAD

**Issue by chivesrs** [cs01/gdbgui#24]
More of a request than an actual issue, but I have a use case where I have a Go binary compiled using gccgo, and use the command line GDB to debug it. I cannot use your tool to debug it due to the non-commercial aspect of the license.

Will you consider modifying the license to one that will allow the use of this tool in commercial settings?

**Comment by cs01** [comment]
Thanks for your interest. I added a link to the README file to accept payment for commercial use ($30 annually per developer).

**Comment by doninphnx** [comment]
I see you

**Comment by cs01** [comment]
The license has been changed to permit commercial use.
