### ISSUE TITLE
Debug executable inside a docker container.  Connection reset.

### ISSUE THREAD

**Issue by bostontrader** [cs01/gdbgui#247]
Hello Folks,

I have gdbgui installed inside a Docker container running Ubuntu 16.04.  I can successfully use it with Firefox by browsing to the default port 5000. I emphasize that Firefox is installed in the container and that I must use various contortions with x11vnc and xvfb to get Firefox output out of the container and visible to a VNC viewer on my host system.

If I run the docker container using -p 5000:5000 I _should_ be able to expose this port to the host.  I _should_ therefore be able to view this from a browser on the host by browsing to localhost:5000.  Alas, I get "connection reset" when I do this.  Any clues re: why this doesn't work would be greatly appreciated.

Thanks

**Comment by bostontrader** [comment]
When all else fails, RTFM!
gdbgui -r

**Comment by pylipp** [comment]
Hej @bostontrader, do you mind sharing how you set up the container to get the firefox output out of the container?

**Comment by bostontrader** [comment]
@pylipp, I'm going to guess that FF in your container wants to use X11 for its GUI action.  In order to get that to work in a container, I use xvfb and x11vnc.  xvfb is a virtual frame buffer that simulates X11 and having this makes GUI apps happy.  I can then use x11vnc to communicate with a vnc viewer outside of the container.  I do a lot of this for several crypto-coin clients at https://github.com/bostontrader/crypto-docker.  Perhaps you can dissect this and find some enlightenment.

You may want to consider just running the gdbgui in the container, and interacting with it via a browser on the host.  In order to do that I've found that I need the -r option when invoking gdbgui.  Apparently this affects the gdbgui binding.  My understanding is that without the -r option, gdbgui can only listen to http from inside the container, but with it, we can connect via docker networking.  So from your browser on the host try connecting to localhost:5000, or whatever address gdbgui gives when it starts.

One other wrinkle with this approach... er, probably with both approaches...
I found that even if I can see gdbgui with my browser, it would not stop on any breakpoints.  This was solved by using the --privileged option when executing an image.  I have a video of how I do this at https://www.patreon.com/posts/ep03-04-getting-25163722

**Comment by pylipp** [comment]
Thanks for the detailed reply! Your second suggestion is totally sufficient for me: In the container I run `gdbgui -r`, and on the host I open the browser at the indicated address.
