### ISSUE TITLE
Passing GDB commands via URL parameter

### ISSUE THREAD

**Issue by lifanxi** [cs01/gdbgui#249]
I'm setting up gdbgui on servers for analyzing core dump files. I have a script to detect new core dump files on the server and send notification emails to administrators. In the notification email, I put a link to gdbgui. However, after opening gdbgui in browser, administrator need to manually input gdb commands to load the core dump file and related symbols to begin investigation. These gdb commands can be generated automatically by my script. So I want to pass these commands via gdbgui URL and when the web GUI is opened, these commands can be executed automatically. 

Is this feature possible to be implemented? If this is not on gdbgui's roadmap, it is possible to give me some instructions on how to implement this by myself? Thank you.

**Comment by cs01** [comment]
> Is this feature possible to be implemented? 

This is a cool idea! Yes this is possible.

> If this is not on gdbgui's roadmap, it is possible to give me some instructions on how to implement this by myself? 

Sure, you will need to 
* parse the argument at the url endpoint (https://github.com/cs01/gdbgui/blob/master/gdbgui/backend.py#L525)
* Pass it to the homepage (same function)
* It will then be a field on `initial_data` (https://github.com/cs01/gdbgui/blob/master/gdbgui/templates/gdbgui.html#L26)
* You can run arbitrary gdb commands by calling `GdbApi.run_gdb_command()` (https://github.com/cs01/gdbgui/blob/master/gdbgui/src/js/GdbApi.jsx#L258)
* A good place to call `run_gdb_command()` is in this function: https://github.com/cs01/gdbgui/blob/master/gdbgui/src/js/gdbgui.jsx#L123

Let me know if you have any other questions. Thank you!
