### ISSUE TITLE
add support for remote debugging

### ISSUE THREAD

**Issue by cs01** [cs01/gdbgui#28]
gdb mi supports remote debugging, i.e. [`-target-select`](https://sourceware.org/gdb/onlinedocs/gdb/GDB_002fMI-Target-Manipulation.html#GDB_002fMI-Target-Manipulation). Add a UI element to choose remote target.

**Comment by cs01** [comment]
I pushed a test branch `dev/add-remote-debugging`. If anyone would like to help out and give a test run, it would be appreciated. 

```
git checkout dev/add-remote-debugging
gdbgui/backend.py --debug
```

![asdf](https://cloud.githubusercontent.com/assets/5715368/23725493/a61095a8-0405-11e7-9aef-8a700d2313c5.png)

**Comment by WojciechMigda** [comment]
This is cool. Is there a way to specify user-defined gdb executable, e.g. gdb-multiarch or arm-linux-gnueabihf-gdb? For the former, gui element to select target architecture would come handy.

**Comment by cs01** [comment]
Run `gdbgui -h` to see the list of arguments.  I believe the the `-g` / `--gdb` argument does what you are looking for. If not let me know.

**Comment by WojciechMigda** [comment]
I'll try it, thanks.

**Comment by WojciechMigda** [comment]
Within bare `gdb-multiarch` I'd execute this:
```
file /repo/github/how-to-qemu-arm-gdb-gtest/hello
set architecture armv5te
set sysroot /usr/arm-linux-gnueabihf/
target remote localhost:1234
```
I repeated the above in the console provided by `gdbgui`. This is screen capture of my browser:
![remote-dgb1](https://cloud.githubusercontent.com/assets/3889167/24081919/2dcde88c-0cbd-11e7-9de5-cf7214554178.png)
Things to note:
1. assembler dump doesn't handle escaped characters,
2. there's a problem with the _registers_ widget - it is empty. Just after executing the `file` command gui displayed red "error" `No registers.` indication at the top of the right panel.
3. after issuing `target remote` error `File not found: None` was displayed in the right panel.
4. even though the "auto add breakpoint to main" is enabled no such breakpoint was set. I had to add it by hand.
5. attached screenshot appears only after issuing `continue`.

In addition I tried the the 'remote debugging' widget. My observations is that it wasn't obvious what to type in the entry box. After few failed attempts I realized that it is simply a wrapper to the `target` command and I have to type `remote` myself.

Remote debugging is already available through the builtin gdb console. In my usecase I am happy with that alone. It would be interesting to hear from other folks who use remote debugging what are their usecases.

**Comment by WojciechMigda** [comment]
Is there a feature for "buttons" assignable with custom commands sequences somewhere on the roadmap?

**Comment by cs01** [comment]
Thanks for the feedback.

> Is there a feature for "buttons" assignable with custom commands sequences somewhere on the roadmap?

No, but if you create an issue I will add it in.

**Comment by WojciechMigda** [comment]
I think I will stay with what `gdb -x` gives. Thanks again and keep it rolling.

**Comment by girtsf** [comment]
(I just stumbled upon gdbgui and gave it a try to see if it works for my needs. I'm using gdb to debug arm-none-eabi targets.)

You asked for feedback on whether this works - the dev branch allows me to connect to the target (if I type "remote :3333"). But I had to run the "file" command by hand to get symbols, and a lot of other stuff didn't work, probably due to arm vs x86 differences. But that's for a different bug.

**Comment by R3AL** [comment]
@girtsf I don't think it's due to arm vs x86 differences.
I tried remote debugging with both host and target x86_64 and I cannot get files to load except headers from /usr/include.

**Comment by cs01** [comment]
Thanks @girtsf @R3AL. Seems like there are enough nuances to this that I would have to connect to a remote target myself and not rely on feedback.

I suspect the problem loading files is that `gdbgui` is trying to load an absolute path on the computer it's running on (your local computer) when it should be loading the path from the remote system (scp from remote, then open locally or something like that). The `/usr/include` files are probably common to both machines which is why they are working.

**Comment by TuxSH** [comment]
> The /usr/include files are probably common to both machines which is why they are working.

I don't think `gdbgui` should make any assumption on the remote, if it does. Ideally gdbgui should be able to debug any target using for example `arm-none-eabi-gdb`, etc.

**Comment by o11c** [comment]
You can easily remote targets using the following:

 * `(gdb) target extended-remote | gdbserver --multi stdio` (should provide full feature-parity with direct gdb usage - but note you'll need to pass several commands to actually get there)
 * `(gdb) target extended remote localhost:$PORT` (parse the port from the first output line of `gdbserver --multi localhost:0` - this is useful if you hit 100% CPU-usage hangs which I've occasionally seen)
 * `(gdb) target remote | gdbserver stdio $PROG $ARGS...` (a single-program experience, more typical for embedded remote targets)
 * `(gdb) target remote | gdbserver --attach stdio $PID`
 * `(gdb) target remote | vgdb --pid=$PID` (for programs started under `valgrind --vgdb=full --vgdb-errors=0`)

I don't think gdbgui currently handles this, but it is an important feature to be able to run *multiple* copies of GDB (not just multiple inferiors in a single GDB), and transparently manage all inferiors regardless of which GDB they're attached to. With twisted (see #65) this should be pretty easy.

**Comment by o11c** [comment]
Oh, and you can work out `sysroot` issues by having a pure-32-bit chroot on a pure-64-bit host.

**Comment by maximevince** [comment]
Hey,
I cannot seem to find your dev/add-remote-debugging branch.
I like the approach and have been looking for a decent gdb UI/GUI for a while now,
always falling back to gdb-tui, by the lack of anything better.

My use-case is especially embedded arm debugging, so "-g /usr/bin/arm-none-eabi-gdb" is a good start, however, it seems it's not behaving correctly, with many "movs\tr0, r0(undefined) undefined+undefined 0x00000018" instructions, and it seems it's not able to reset/halt/step the remote target.

**Comment by cs01** [comment]
@maximevince I removed the branch yesterday because it was getting pretty old. I just pushed it back so you can try it, but that branch lacks lots of newer features. I'm working on a rewrite of gdbgui's frontend to react (`rewrite-to-react-components`, under heavy dev), and would still like to add support for remote debugging.

When you say it's not behaving correctly, is that while you using gdbgui and its terminal widget, or gdb tui, or something else?

**Comment by cs01** [comment]
Since there is a command line built in, and that can be used for remote debugging, I'm going to close since there is a valid workaround.

**Comment by cs01** [comment]
This has been added in version 0.10+. 

![image](https://user-images.githubusercontent.com/5715368/35199464-d4b4d0c4-feb2-11e7-938a-75d0c4778db0.png)

(I know I said I wouldn't do it, but I couldn't help myself :smile:)
