### ISSUE TITLE
build.js not found (404) after fresh installation from AUR

### ISSUE THREAD

**Issue by Marenz** [cs01/gdbgui#288]
**To Reproduce**
1. Install from AUR
2. Run `gdbgui` in terminal
3. Change to browser
4. Read `Loading application, please wait. Note: JavaScript and cookies must be enabled.`
5. Check browser console. Read: `GET http://127.0.0.1:5000/static/js/build.js?_=0.13.2.0 net::ERR_ABORTED 404 (NOT FOUND)`
6. Check source of call: `<script type="text/javascript" src="static/js/build.js?_=0.13.2.0"></script>`

**Expected behavior**
Interface should load

**Please complete the following information:**
* OS: ArchLinux x64
* gdbgui version (`gdbgui -v`): 0.13.2.0-1
* gdb version (`gdb -v`): 8.3
* browser [e.g. chrome, safari]: vivaldi / chromium / firefox
* python packages (`pip freeze`):
No pip available, but those are the installed python packages:
```
local/python-apipkg 1.5-1
local/python-appdirs 1.4.3-2
local/python-atomicwrites 1.3.0-1
local/python-attrs 19.1.0-1
local/python-blinker 1.4-4
local/python-cairo 1.18.1-1
local/python-click 7.0-1
local/python-dateutil 2.8.0-1
local/python-dbus 1.2.8-2
local/python-dbus-common 1.2.8-2
local/python-docutils 0.14-2
local/python-engineio 3.3.1-1
local/python-feedgenerator 1.9-4
local/python-flask-compress 1.4.0-1
local/python-flask-socketio2 2.9.6-2
local/python-flask12 0.12.4-2
local/python-gdbgui 0.13.2.0-1
local/python-gevent 1.4.0-1
local/python-gobject 3.32.2-1
local/python-greenlet 0.4.15-1
local/python-importlib-metadata 0.19-1
local/python-iniconfig 1.0.0-2
local/python-itsdangerous 1.1.0-1
local/python-jinja 2.10.1-1
local/python-markupsafe 1.1.1-1
local/python-more-itertools 4.3.0-1
local/python-nose 1.3.7-4
local/python-packaging 19.0-1
local/python-pluggy 0.12.0-1
local/python-py 1.8.0-1
local/python-pygdbmi 0.9.0.0-2
local/python-pygments 2.4.2-1
local/python-pyparsing 2.4.2-1
local/python-pytest 5.0.1-1
local/python-pytz 2019.2-1
local/python-setuptools 1:41.0.1-1
local/python-six 1.12.0-1
local/python-socketio 3.1.2-1
local/python-unidecode 1.1.1-1
local/python-urllib3 1.25.3-1
local/python-venusian 1.2.0-2
local/python-wcwidth 0.1.7-3
local/python-websocket-client 0.56.0-1
local/python-websockets 7.0-2
local/python-werkzeug 0.15.2-1
local/python-wiring 0.4.0-1
local/python-wrapt 1.11.2-1
local/python-xdg 0.26-2
local/python-yapsy 1.12.2-1
local/python-zipp 0.5.2-1
```

**Comment by Marenz** [comment]
Also, here is the debug log:
```
❰marenz❙~❱✔≻ gdbgui --debug
failed to initialize socketio app with async mode "eventlet". Continuing with async mode "threading".
View gdbgui at http://127.0.0.1:5000
exit gdbgui by pressing CTRL+C
WebSocket transport not available. Install eventlet or gevent and gevent-websocket for improved performance.
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
failed to initialize socketio app with async mode "eventlet". Continuing with async mode "threading".
View gdbgui at http://127.0.0.1:5000
exit gdbgui by pressing CTRL+C
WebSocket transport not available. Install eventlet or gevent and gevent-websocket for improved performance.
 * Debugger is active!
 * Debugger PIN: 131-323-684



127.0.0.1 - - [12/Aug/2019 14:16:06] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [12/Aug/2019 14:16:06] "GET /static/js/build.js?_=0.13.2.0 HTTP/1.1" 404 -
127.0.0.1 - - [12/Aug/2019 14:16:07] "GET /static/vendor/css/bootstrap.min.css.map HTTP/1.1" 404 -
127.0.0.1 - - [12/Aug/2019 14:16:07] "GET /static/js/build.js?_=0.13.2.0 HTTP/1.1" 404 -
127.0.0.1 - - [12/Aug/2019 14:16:07] "GET /static/vendor/js/awesomplete.min.js.map HTTP/1.1" 404 -
127.0.0.1 - - [12/Aug/2019 14:16:07] "GET /static/vendor/js/vis.map HTTP/1.1" 404 -
127.0.0.1 - - [12/Aug/2019 14:16:07] "GET /static/vendor/css/awesomplete.css.map HTTP/1.1" 404 -
127.0.0.1 - - [12/Aug/2019 14:16:07] "GET /static/favicon.ico HTTP/1.1" 200 -
```

**Comment by Marenz** [comment]
Another person also has problems using the same package so this might be a packaging issue. See https://aur.archlinux.org/packages/python-gdbgui/

**Comment by Technifocal** [comment]
I am also receiving this issue, first time using this software, also installed via AUR. Mine is just failing with the build.js:

```
$ gdbgui --debug                                                                                                                                                                                    
failed to initialize socketio app with async mode "eventlet". Continuing with async mode "threading".
View gdbgui at http://127.0.0.1:5000
exit gdbgui by pressing CTRL+C
WebSocket transport not available. Install eventlet or gevent and gevent-websocket for improved performance.
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
failed to initialize socketio app with async mode "eventlet". Continuing with async mode "threading".
View gdbgui at http://127.0.0.1:5000
exit gdbgui by pressing CTRL+C
WebSocket transport not available. Install eventlet or gevent and gevent-websocket for improved performance.
 * Debugger is active!
 * Debugger PIN: 103-605-247
127.0.0.1 - - [12/Aug/2019 14:23:25] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [12/Aug/2019 14:23:25] "GET /static/js/build.js?_=0.13.2.0 HTTP/1.1" 404 -
```

**Comment by cs01** [comment]
That build file used to included in gdbgui’s source code. Going forward the AUR package maintainer will need to build that file themselves before publishing the AUR package.

**Comment by cs01** [comment]
Is there a reason the AUR package must be used? https://www.gdbgui.com/installation/ Has installation instructions that allow you to use pip, pipx, or run a prebuilt binary.  That might get you going in the short term while the AUR package is updated.

**Comment by ZWindL** [comment]
@cs01 I'm the maintainer of this aur package, issue is fixed now.
About why I prefer to use system package manager to manage software is really just a matter of personal preference, there's lots of different kind of packages managed by different package manager (e.g. npm, pip, a pipx in this case), it messed environment up and hard to maintain for me, I want to use as less commands/tools as it could be to maintain software/package update, rather than run series commands just for updating several packages.

**Comment by cs01** [comment]
@ZWindL thank you for taking the time to maintain the gdbgui package on AUR. I am glad you were able to work around the build.js file not being included in the gdbgui source code anymore.

I totally understand frustrations with packaging and installation so if AUR is easier then by all means, go for it 😄 .

**Comment by ZWindL** [comment]
@cs01 also thanks for your hard working of this amazing software, it really easy to use.
And this issue may should be closed now? @Marenz
