### ISSUE TITLE
unable to interrupt a process

### ISSUE THREAD

**Issue by shi-yan** [cs01/gdbgui#31]
with gdb, if I press control + c, I can stop the current process,

with gdbgui, there is no pause button.

there is an int button, which I thought was a pause button, but it doesn't seem to be the case.

**Comment by cs01** [comment]
Try this and let me know if it behaves as expected:

`handle SIGINT stop`
http://stackoverflow.com/a/25092973/2893090

**Comment by cs01** [comment]
@shi-yan have you tried my suggestion? Any updates?

**Comment by o11c** [comment]
My library (see #65) should handle this easily.
