### ISSUE TITLE
No such file or directory / file not found (source code will not display/show up)

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [cs01/gdbgui#332]
**Describe the bug**
I cannot get the source files to show up at all. Note that I'm running `gdbgui -r` on a remote server which I am sshed into. We are on the same VPN. I built the executable with clang options `-ggdb -O0`.

**To Reproduce**

1. On the remote server, run `gdbgui -r`. It will show the following, for example:

        $ gdbgui -r
        Warning: authentication is recommended when serving on a publicly accessible IP address. See gdbgui --help.
        View gdbgui at http://10.70.33.56:5000
        exit gdbgui by pressing CTRL+C

1. On your local machine, open up Chrome to http://10.70.33.56:5000. Copy and paste your executable path into the "load binary" field. Ex: `/home/$USER/.cache/bin/path/to/my/executable`.
1. Click "Load Binary". The center window now shows `file not found: /proc/self/cwd/path/to/my/executable/main.cpp`
1. Attempting to "Fetch source files" by typing in the correct path doesn't work. 
1. Running gdb manually with `run` shows the `No such file or directory.` error when it tries to display the source code line.

**Expected behavior**
I expect to either have the source code show up automatically when I click "Load Binary", or to show up after I manually specify the exact path to `main.cpp` and click "Fetch source files." Neither of those cases work.

**Please complete the following information:**
* OS: Ubuntu 18.04 on both the remote server where `gdbgui` is installed, and on my local machine where it is NOT installed, but I am accessing it through the browser, from the remote server.
* gdbgui version (`gdbgui -v`): 0.13.2.0
* gdb version (`gdb -v`): GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
* browser [e.g. chrome, safari]: Chrome
* python packages (`pip freeze`): 

**Additional context**
I've never used `gdbgui` before and I am pretty new to `gdb` too.

**Comment by cs01** [comment]
It is trying to open files on the remote machine. Does `/proc/self/cwd/path/to/my/executable/main.cpp` exist on the remote machine?

If not, but it does exist *somewhere* on the remote machine, you can remap the path with the following argument:
```
  --remap-sources REMAP_SOURCES, -m REMAP_SOURCES
                        Replace compile-time source paths to local source paths. Pass valid JSON key/value pairs.i.e. --remap-
                        sources='{"/buildmachine": "/path/on/remote/machine"}'
```

**Comment by ElectricRCAircraftGuy** [comment]
I looked at `gdbgui -h`, and found the `--remap-sources` option. This seems to be the solution:

```
gdbgui -r --project /path/to/my/source/rootdir --remap-sources='{"/proc/self/cwd/": "/path/to/my/source/rootdir"}'
```

----

However, I seem to have a new problem: my `printf()` statements to stdout are not showing up in the console, but when I run `gdb /path/to/my/executable` manually, it works fine.

**Comment by ElectricRCAircraftGuy** [comment]
Where did this path get set? `/proc/self/cwd/` 

Is this set at build time by my build system?

**Comment by cs01** [comment]
> my printf() statements to stdout are not showing up in the console, but when I run gdb /path/to/my/executable manually, it works fine.

Hmm not sure what that's not working. This is a pretty hacky solution, but you could ssh into the remote machine, get the tty name (by running `tty`), and then redirect output to that tty in gdb with `set inferior-tty /dev/ttys3  # replace /dev/ttys3 with desired tty name`.

> Where did this path get set? /proc/self/cwd/ Is this set at build time by my build system?

Yes it was set during the build process by whichever compiler was used. The debug symbols generated by the compiler contain that path. For example, gcc would set it at compile time with the `-g` flag.

**Comment by ElectricRCAircraftGuy** [comment]
On the remote machine I ran `tty` and got this:
```
$ tty
/dev/pts/11

```

So on the local machine in the gdbgui browser window console at the bottom I typed:
```
set inferior-tty /dev/pts/11
```

Now  the strangest thing is happening. As I run the gdbgui and step over `printf()` statements, they are magically appearing inside only one of my many `tmux` windows I have open, sshed into the remote machine! There's not even a process open in that tmux terminal. The printf statements just magically show up there though!

**Comment by ElectricRCAircraftGuy** [comment]
I closed and restored the remote tmux sessions and can't seem to duplicate the behavior, but gdbgui still won't print the output from `printf()` statements.

**Comment by ElectricRCAircraftGuy** [comment]
Let's continue the debugging of the `printf()` problem here: https://github.com/cs01/gdbgui/issues/333. I'll close this issue since I was able to solve it with `--remap-sources='{"/proc/self/cwd/": "/path/to/my/source/rootdir"}'` here: https://github.com/cs01/gdbgui/issues/332#issuecomment-648396024
