### ISSUE TITLE
Cannot debug googletest unit test programs: 'Function "main" not defined'

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [cs01/gdbgui#344]
**Describe the bug**

**To Reproduce**
1. Build a unit test where you are utilizing the [googletest](https://github.com/google/googletest) library for performing unit tests on your code.
1. Launch `gdbgui` from inside the root dir of your project containing your source code. 
1. In gdbgui, add an absolute path to your built unit test executable and click the "Load Binary" button.
1. The gdb window says `Function "main" not defined.`

**Expected behavior**

I expected the source code to show up in gdbgui, and to be able to debug the program. Even if I manually use the gdb command `file /my/path/to/executable` inside gdbgui and then try to `run` it, it won't work in gdbgui. But, in plain old `gdb` in the terminal, I can run and debug the whole thing just fine. 

**Screenshots**
![image](https://user-images.githubusercontent.com/6842199/90074174-819a9300-dcaf-11ea-8136-093241f2fd17.png)

**Please complete the following information:**
* OS: Ubuntu 18.04
* gdbgui version (`gdbgui -v`): 0.13.2.1
* gdb version (`gdb -v`): GNU gdb (Ubuntu 8.1-0ubuntu3.2) 8.1.0.20180409-git
* browser [e.g. chrome, safari]: chrome
* python packages (`pip freeze`): 

**Additional context**
NA

**Comment by cs01** [comment]
Did you ever get this working?

**Comment by cs01** [comment]
I just gave it a shot and it worked fine. Maybe the main function was missing in your compiled executable, or symbols weren't available due to compiler flags. 
![image](https://user-images.githubusercontent.com/5715368/91651242-256d9800-ea3f-11ea-9e1a-6a2b9c32cd98.png)

**Comment by cs01** [comment]
Maybe you need to compile with `-lgtest_main`?
