### ISSUE TITLE
Sierra

### ISSUE THREAD

**Issue by jdiego** [cs01/gdbgui#35]
On 10.12 (Sierra) or later with SIP, we need to run this:

  `echo "set startup-with-shell off" >> ~/.gdbinit`

So, we on Mac Sierra we need to add an extra argument on the GdbController.  Something like this:
 ```python
        gdb_args=['-nx', '--interpreter=mi2']
        # checking the current operating system
        if sys.platform == "darwin":
            gdb_args.append('--init-eval-command=set startup-with-shell off')
        #
        _gdb[request.sid] = GdbController(gdb_path=GDB_PATH, gdb_args=gdb_args)

```
I'm submitting a patch file to you, If you like my work then we can apply it. 
[backend.patch.txt](https://github.com/cs01/gdbgui/files/819000/backend.patch.txt)

**Comment by cs01** [comment]
Thanks for making this. It looks like it adds the argument if you're running a mac, but it seems like it should be conditional based on mac and the os version.

**Comment by tijme** [comment]
@jdiego Thanks, works for me!

**Comment by cs01** [comment]
@jdiego or @tijme  I don't have a mac, so I can't test the change myself. Could you provide the output of the following python code so we can make the logic only apply to mac versions >= 10.12?

```
>>> import platform
>>> platform.platform()
```

**Comment by tijme** [comment]
@cs01 `Darwin-16.4.0-x86_64-i386-64bit`
