### ISSUE TITLE
Error in greenlet with Python 3.9.0 on macOS: TypeError: type() takes 1 or 3 arguments

### ISSUE THREAD

**Issue by fxcoudert** [cs01/gdbgui#359]
**Describe the bug**
We're testing the migration of gdb and gdbgui to Python 3.9.0 as part of Homebrew: https://github.com/Homebrew/homebrew-core/pull/62792

**To Reproduce**
Launch `gdbgui` and connect to it (see below).

**Error**

```
==> /usr/local/Cellar/gdbgui/0.14.0.1_1/bin/gdbgui -v
==> curl -s 127.0.0.1:51050
Traceback (most recent call last):
  File "/usr/local/Cellar/gdbgui/0.14.0.1_1/libexec/lib/python3.9/site-packages/gevent/baseserver.py", line 246, in _do_read
    self.do_handle(*args)
  File "/usr/local/Cellar/gdbgui/0.14.0.1_1/libexec/lib/python3.9/site-packages/gevent/baseserver.py", line 208, in do_handle
    spawn(_handle_and_close_when_done, handle, close, args)
  File "src/gevent/greenlet.py", line 662, in gevent._greenlet.Greenlet.spawn
TypeError: type() takes 1 or 3 arguments
2020-10-13T09:44:35Z ((('127.0.0.1', 51051),), <WSGIServer at 0x105f15a00 fileno=5 address=127.0.0.1:51050>) failed with TypeError
```

**Please complete the following information:**
* OS: macOS 10.13 to 10.15
* gdbgui version (`gdbgui -v`): 0.14.0.1
* gdb version (`gdb -v`): 9.2

**Comment by ksherlock** [comment]
This line in gevent:

https://github.com/gevent/gevent/blob/18365b99bb458261e04b0e36bf8b57926e9ae194/src/gevent/greenlet.py#L1131

might be the issue.

in gevent/baseserver.py:

with acceleration:

* Greenlet: <class 'gevent._greenlet.Greenlet'>
* Greenlet.spawn: <bound method Greenlet.spawn of <class 'type'>>

without acceleration:

* Greenlet: <class 'gevent.greenlet.Greenlet'>
* Greenlet.spawn: <bound method Greenlet.spawn of <class 'gevent.greenlet.Greenlet'>>

setting the `PURE_PYTHON=1` environment variable skips the accelerator stuff so it can be run that way as well.

**Comment by ryanfuji** [comment]
export PURE_PYTHON=1, fixed the issue for me 
Catalina 10.15.7
Python 3.9
GDB 10.2
gdbgui 0.14

**Comment by denysvitali** [comment]
Indeed, `export PURE_PYTHON=1` solves the issue for me too:

```
$ gdbgui -v
0.14.0.1
$ python --version
Python 3.9.1
$ cat /etc/os-release | head -n1 | cut -f 2 -d = | sed 's/"//g'
Arch Linux
```

**Comment by callahanp** [comment]
adding export PURE_PYTHON=1 solves the issue on Lubuntu  21.04 

Lubuntu 21.04
Python 3.9.4
pip 20.3.4 from /usr/lib/python3/dist-packages/pip (python 3.9)
pipx 0.16.2.1
gdbgui 0.14.0.2

**Comment by 1Mark** [comment]
`PURE_PYTHON=1 gdbgui` or `gdbgui --debug` both work for me, but this really should be fixed.

**Comment by cs01** [comment]
Pull requests are welcome

**Comment by Igosuki** [comment]
Same thing on Linux Ubuntu 21.04

**Comment by bryanmobrien** [comment]
Same (PURE_PYTHON=1  gdbgui  "works") on: 
macOS Big Sur 11.5.2
python 3.9.5
pip 21.2.4
gdbgui 0.14.0.2

**Comment by cs01** [comment]
eventlet and gevent have been removed as dependencies. This should work fine now in v0.15. Thanks everyone for reporting.
