### ISSUE TITLE
gdbgui installation issue

### ISSUE THREAD

**Issue by Karthik72644** [cs01/gdbgui#372]
Hi, I am trying to install gdbgui on windows 10 machine using cygwin. Installation fails when it trys to build wheels for gevent (PEP 517). I tried with "pip3 install --no-binary :all: gdbgui" still it fails at the same step. I am using Python version 3.8.

Could someone guide me on this?

---- here is excerpt from console window-------

$ pip3 install --no-binary :all: gdbgui
Collecting gdbgui
  Using cached gdbgui-0.14.0.2.tar.gz (1.4 MB)
Requirement already satisfied: gevent-websocket<0.11,>=0.10.1 in /usr/local/libpython3.8/site-packages (from gdbgui) (0.10.1)
Collecting greenlet==0.4.16
  Using cached greenlet-0.4.16.tar.gz (60 kB)
Collecting eventlet<0.26,>=0.25.0
  Using cached eventlet-0.25.2.tar.gz (397 kB)
Requirement already satisfied: six>=1.10.0 in /usr/lib/python3.8/site-packages from eventlet<0.26,>=0.25.0->gdbgui) (1.15.0)
Collecting dnspython>=1.15.0
  Using cached dnspython-2.0.0.zip (324 kB)
Collecting Flask<1.0,>=0.12.2
  Using cached Flask-0.12.5.tar.gz (621 kB)
Requirement already satisfied: click>=2.0 in /home/KarthikSangi/.local/lib/pythn3.8/site-packages (from Flask<1.0,>=0.12.2->gdbgui) (7.1.2)
Collecting Flask-Compress<2.0,>=1.4.0
  Using cached Flask-Compress-1.8.0.tar.gz (10 kB)
Collecting Flask-SocketIO<3.0,>=2.9
  Using cached Flask-SocketIO-2.9.6.tar.gz (14 kB)
Collecting gevent<2.0,>=1.2.2
  Using cached gevent-1.5.0.tar.gz (5.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting itsdangerous>=0.21
  Using cached itsdangerous-1.1.0.tar.gz (53 kB)
Collecting Jinja2>=2.4
  Using cached Jinja2-2.11.2.tar.gz (257 kB)
Collecting MarkupSafe>=0.23
  Using cached MarkupSafe-1.1.1.tar.gz (19 kB)
Collecting monotonic>=1.4
  Using cached monotonic-1.5.tar.gz (7.5 kB)
Collecting pygdbmi<0.11,>=0.10.0.0b0
  Using cached pygdbmi-0.10.0.0.tar.gz (18 kB)
Collecting Pygments<3.0,>=2.2.0
  Using cached Pygments-2.7.3.tar.gz (2.4 MB)
Collecting python-socketio<5.0,>=4.6.1
  Using cached python-socketio-4.6.1.tar.gz (42 kB)
Collecting python-engineio<4,>=3.13.0
  Using cached python-engineio-3.14.2.tar.gz (40 kB)
Collecting Werkzeug<1.0,>=0.7
  Using cached Werkzeug-0.16.1.tar.gz (935 kB)
Collecting brotli
  Using cached Brotli-1.0.9.zip (510 kB)
Skipping wheel build for gdbgui, due to binaries being disabled for it.
Skipping wheel build for greenlet, due to binaries being disabled for it.
Skipping wheel build for eventlet, due to binaries being disabled for it.
Skipping wheel build for dnspython, due to binaries being disabled for it.
Skipping wheel build for Flask, due to binaries being disabled for it.
Skipping wheel build for Flask-Compress, due to binaries being disabled for it.
Skipping wheel build for Flask-SocketIO, due to binaries being disabled for it.
Skipping wheel build for itsdangerous, due to binaries being disabled for it.
Skipping wheel build for Jinja2, due to binaries being disabled for it.
Skipping wheel build for MarkupSafe, due to binaries being disabled for it.
Skipping wheel build for monotonic, due to binaries being disabled for it.
Skipping wheel build for pygdbmi, due to binaries being disabled for it.
Skipping wheel build for Pygments, due to binaries being disabled for it.
Skipping wheel build for python-socketio, due to binaries being disabled for it
Skipping wheel build for python-engineio, due to binaries being disabled for it
Skipping wheel build for Werkzeug, due to binaries being disabled for it.
Skipping wheel build for brotli, due to binaries being disabled for it.
Building wheels for collected packages: gevent
  Building wheel for gevent (PEP 517) ... error
  ERROR: Command errored out with exit status 1:

---------------------------------------------------------------------------

**Comment by cs01** [comment]
```
Building wheel for gevent (PEP 517) ... error
```
Looks like there is a problem with gevent. Here is what thier page has to say about installation http://www.gevent.org/install.html. Maybe looking around their github page and searching the issues for that error message will yield some results. https://github.com/gevent/gevent/issues

**Comment by cs01** [comment]
Another option is to use an a prebuilt gdbgui executable. If you need a windows release, you can use https://github.com/cs01/gdbgui/releases/tag/v0.13.2.1.

**Comment by Karthik72644** [comment]
> ```
> Building wheel for gevent (PEP 517) ... error
> ```
> 
> Looks like there is a problem with gevent. Here is what their page has to say about installation http://www.gevent.org/install.html. If that doesn't help, maybe looking around their github page and searching the issues for that error message will yield some results. https://github.com/gevent/gevent/issues

Chad thanks for your quick response... i tried installing greenlet and then gevent asmentioned in the gevent.org website still issue continues.

**Comment by Karthik72644** [comment]
> Another option is to use an a prebuilt gdbgui executable. If you need a windows release, you can use https://github.com/cs01/gdbgui/releases/tag/v0.13.2.1.

I tried the prebuilt exe it works. Can I use gdbgui with openocd? At present I am using gdb + openocd for stm32 debugging can gdbgui replace that? if so are there any examples on the setup? please share if you know anything on this...

**Comment by MattBJ** [comment]
Here's something that can help you isolate your issue.
Create a working directory for gdbgui (linux: `mkdir gdbguiDir`)
inside that directory:
`python3 -m venv .` --> This will create a virtual environment
For linux, next:
`source bin/activate` --> Sets up a compartmentalized $PATH environment variable for pip
Then from here you can pip install gdbgui and it'll be separated from all your other pip installs.

If anything is conflicting with gdbgui like that, then this should help. Otherwise, at least it makes certain your other modules aren't conflicting

**Comment by Karthik72644** [comment]
Matt,
Thank you the info
I will try it and let you know how it goes
