### ISSUE TITLE
error: could not create '/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/greenlet': Operation not permitted

### ISSUE THREAD

**Issue by cdoco** [cs01/gdbgui#38]
`  Running setup.py install for greenlet ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-WSfAmC/greenlet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-6W38jX-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'greenlet' extension
    creating build
    creating build/temp.macosx-10.12-intel-2.7
    cc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -arch i386 -pipe -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c greenlet.c -o build/temp.macosx-10.12-intel-2.7/greenlet.o
    creating build/lib.macosx-10.12-intel-2.7
    cc -bundle -undefined dynamic_lookup -arch x86_64 -arch i386 -Wl,-F. build/temp.macosx-10.12-intel-2.7/greenlet.o -o build/lib.macosx-10.12-intel-2.7/greenlet.so
    running install_lib
    copying build/lib.macosx-10.12-intel-2.7/greenlet.so -> /Library/Python/2.7/site-packages
    running install_headers
    creating /System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/greenlet
    error: could not create '/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/greenlet': Operation not permitted

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-WSfAmC/greenlet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-6W38jX-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-WSfAmC/greenlet/`

**Comment by cs01** [comment]
Could you show me which command you are running? It looks like you don't have write access to a folder. 

Just a shot in the dark, but try running with `sudo` at the start of whichever command you're running.

**Comment by cdoco** [comment]
I run `sudo pip install gdbgui --upgrade`, And then there's the mistake。

My system version is OSX 10.12.3.

**Comment by cs01** [comment]
I did a search for your error and it looks like a common problem on newer versions of Mac OS. See http://apple.stackexchange.com/questions/209572/how-to-use-pip-after-the-os-x-el-capitan-upgrade

Let me know what works for you and I will update the documentation.  Thanks.

**Comment by cdoco** [comment]
I use `sudo pip install --user gdbgui --upgrade` to run it and install it successfully, Thanks.

On newer versions of Mac OS to need to add `--user` parameters.

Thanks.

**Comment by zouhuibo** [comment]
Yes, I have this error. Thanks!

**Comment by cs01** [comment]
@zouhuibo did you get this working? 

`sudo pip install gdbgui --upgrade --user` is already in the Installation instructions in the README (thanks to @cdoco)
