### ISSUE TITLE
Why no Windows and 32-bits support?

### ISSUE THREAD

**Issue by xtexChooser** [cs01/gdbgui#395]
Why v0.14 does not supported windows?

May provide i686(32-bits) Windows executable file?

**Comment by cs01** [comment]
v0.14 uses pty’s for a better terminal interface in the browser, which unfortunately Python does not support on windows. The release notes mention more detail on this if you are interested. I filed a bug on the CPython issue tracker but I doubt anything will happen with it. 

v0.13 and earlier still work on windows.
