### ISSUE TITLE
Using GDB commands that updates the current command should update the UI

### ISSUE THREAD

**Issue by kfir-drivenets** [cs01/gdbgui#40]
When using a command that changes the current instruction, for example "next", the current line in the UI should change.
This should be the same as pressing the relevant button in the GUI.

Simple suggestion: after each gdb command that is executed get the current line in GDB and if needed update the UI.

**Comment by qiang-bi** [comment]
Can you explain what you mean by "current line" in UI changes?
Mine works fine as when I enter next or click button, the highlighting line in GUI is updated, so is the line number in call stack.

**Comment by kfir-drivenets** [comment]
I hope that the following pictures will make it clearer :)

The following picture is a screen shot that shows what happens if I run using "n"
<img width="1437" alt="screen shot 2017-03-06 at 9 35 00 pm" src="https://cloud.githubusercontent.com/assets/21293663/23626255/dfde11d6-02b4-11e7-9080-8538bba661d3.png">

In this picture I clicked the next button 
<img width="1440" alt="screen shot 2017-03-06 at 9 37 23 pm" src="https://cloud.githubusercontent.com/assets/21293663/23626334/2a888310-02b5-11e7-99cf-08e1cf4e81bb.png">

**Comment by cs01** [comment]
You are right @kfir-drivenets, gdbgui does not react the same to non-machine-interface commands as it does to MI commands. 

Making it refresh state after each user non-mi command entered by the user shouldn't be too hard to add. Thanks for submitting the description, solution, and screenshots. Makes my job easier.
