### ISSUE TITLE
Cannot install v0.15.0.0 from PyPI source due to missing requirements.in

### ISSUE THREAD

**Issue by cho-m** [cs01/gdbgui#403]
**Describe the bug**
`setup.py` references `requirements.in`:
https://github.com/cs01/gdbgui/blob/6c06eae6ca790de695be37cff3a79bd01124d729/setup.py#L63

However, this is not part of PyPI source, which causes build to fail when running `pip install ... </path/to/extracted/gdbgui-0.15.0.0>`:
```
    Running setup.py (path:/private/tmp/pip-req-build-1po4_ych/setup.py) egg_info for package from file:///private/tmp/gdbgui-20210901-83182-1vvs9i1/gdbgui-0.15.0.0
    Created temporary directory: /private/tmp/pip-pip-egg-info-yevhhffb
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-req-build-1po4_ych/setup.py", line 62, in <module>
        install_requires=distutils.text_file.TextFile(
      File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/text_file.py", line 100, in __init__
        self.open(filename)
      File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/text_file.py", line 115, in open
        self.file = io.open(self.filename, 'r', errors=self.errors)
    FileNotFoundError: [Errno 2] No such file or directory: './requirements.in'
WARNING: Discarding file:///private/tmp/gdbgui-20210901-83182-1vvs9i1/gdbgui-0.15.0.0. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

This was seen in Homebrew https://github.com/Homebrew/homebrew-core/pull/84405

**To Reproduce**
Steps to reproduce the behavior (based on Homebrew installation process):
1. Download and extract PyPI source https://files.pythonhosted.org/packages/da/b4/c8419e2c6683d76df93f918a964940965040fde82a29e493b062c22baa62/gdbgui-0.15.0.0.tar.gz
2. Set up virtualenv and install all dependencies
3. Install `gdbgui` from extracted source: `pip install -v --no-deps --no-binary :all: --ignore-installed </path/to/extracted/gdbgui-0.15.0.0>`

**Expected behavior**
Successfully builds & installs `gdbgui` using PyPI source

**Screenshots**
N/A

**Please complete the following information:**
* OS: macOS and Linux
* gdbgui version (`gdbgui -v`): 0.15.0.0
* gdb version (`gdb -v`):
* browser [e.g. chrome, safari]:
* python packages (`pip freeze`):

**Additional context**
See Homebrew PR. Current work around issue by manually setting up the missing requirements.in file.

**Comment by cs01** [comment]
Thanks. I see I excluded the file from MANIFEST.in when I should have included it. I’ll fix and release a new version.
