### ISSUE TITLE
Unable to find Mach task port

### ISSUE THREAD

**Issue by BookOwl** [cs01/gdbgui#55]
I'm trying to use this program, but I get the following error in the GUI:
`Unable to find Mach task port for process-id 19311: (os/kern) failure (0x5).\n (please check gdb is codesigned - see taskgated(8))`

I'm on OSX 10.11 and installed gdb through homebrew

**Comment by cs01** [comment]
Check out this link, it should fix your problem: https://gcc.gnu.org/onlinedocs/gnat_ugn/Codesigning-the-Debugger.html

**Comment by ray-kim-12** [comment]
I have followed the step by step process but am now getting the following error after I change the 'specify a location for the certificate screen' from login to 'System':

> Unknown Error = -2,147,414,007

My OS is High Sierra.

Thanks for your help

**Comment by cs01** [comment]
Check out these links

https://apple.stackexchange.com/questions/309017/unknown-error-2-147-414-007-on-creating-certificate-with-certificate-assist

https://apple.stackexchange.com/questions/302866/keychain-access-error-when-creating-new-system-certificate

https://gist.github.com/gravitylow/fb595186ce6068537a6e9da6d8b5b96d

**Comment by alsydrm** [comment]
This solution doesn't work on my macOS Mojave. Can someone help me?

**Comment by tgglv** [comment]
@alsydrm 
I had the same problem when tried to debug my Golang code.
Described solution doesn't work for me too but I find out that I can use `lldb` instead of `gdb`.

**Comment by dmarinescu** [comment]
confirm advice not working on any new/modern macos (so called operating system)
apple sucks (for lack of a better word)

**Comment by cs01** [comment]
Whatever the root cause of this is, it affects all gdb users and it not inherently related to gdbgui. I would recommend googling around to try to find a recent workaround (or conclusive proof that gdb cannot work on Mojave).
