### ISSUE TITLE
crashes upon loading in browser (windows)

### ISSUE THREAD

**Issue by ayovev511** [cs01/gdbgui#59]
I installed gdbgui but as soon as I try to run it, it opens up a window in the browser and then immediately crashes followed by a traceback that is printed saying that it "cannot import name 'POINTER'" (screenshot attached). Is there something I'm doing wrong? Any help would be appreciated, thank you

![issuescreen](https://cloud.githubusercontent.com/assets/10277014/24824252/caa4a57a-1bbc-11e7-924b-0ffe91b52daa.png)

**Comment by cs01** [comment]
Thanks for taking the time to report this, sorry this is happening.

This is a windows-specific issue, and unfortunately I don't do much development on windows. 

The `ctypes` modules is built into Python's standard library. It looks like you're using Python 3.6. The python 3 [documentation](https://docs.python.org/3/library/ctypes.html#ctypes.POINTER) shows that `POINTER` is a function in the `ctypes` module, not in `cytpes.wintypes` as your screenshot shows. This might be a bug in [pygdbmi](https://github.com/cs01/pygdbmi).

If you have the time and are up for it, you try a potential fix.

In the `pygdbmi` package, open the file `gdbcontroller.py` and change 
```
        from ctypes import windll, byref, wintypes, WinError
        from ctypes.wintypes import HANDLE, DWORD, POINTER, BOOL
```

to 

```
        from ctypes import windll, byref, wintypes, WinError, POINTER
        from ctypes.wintypes import HANDLE, DWORD, BOOL
```

(move the `POINTER` import to the previous line)

**Comment by ayovev511** [comment]
Looks like that fixed the browser crash issue but now for some reason it just opens the tab but doesn't do anything even when I prompt gdb to 'start' debugging. Looks like I'll just stick to the CLI version of gdb, but nonetheless awesome program! :-)

**Comment by cs01** [comment]
Thanks for letting me know. Again, sorry for the inconvenience. If you ever feel like it, you could try running it with [cygwin](https://cygwin.com/), or you could try Visual Studio. I hear they have a good debugger.

**Comment by cs01** [comment]
Closed since windows is not natively supported by gdbgui at this time. If using windows, cygwin can be used to run gdbgui.
