### ISSUE TITLE
Not able to Tamper/Disassemble any iOS App using GDB-GUI

### ISSUE THREAD

**Issue by kryptoknight13** [cs01/gdbgui#60]
Can you help with exact steps for disassembling binaries using gdb-gui?

**Comment by cs01** [comment]
Sorry you are experiencing trouble with this. 

To view disassembly

- Load an executable file that was compiled from C, C++, go, or rust
- Insert one or more breakpoints
- Run the program until it hits the breakpoint
- Click the "disassemble" checkbox

gdbgui will then fetch disassembly for 30 lines of code, starting at the line you are paused on.

**Comment by ColdHeat** [comment]
I seem to have trouble doing this as well with a regular C program without source. 

I do:

```
b main
r
```

and then hit the"fetch disassembly" button but I get no disassembly :(

**Comment by cs01** [comment]
@ColdHeat The "fetch disassembly" button in gdbgui works by knowing which file and line to get disassembly for. If the source was compiled without the `-g` flag, then gdb doesn't have the link between the source code and the breakpoints, and therefore gdbgui doesn't even try to fetch it (it uses this command: `-data-disassemble -f ${fullname} -l ${start_line} -n 100 -- ${mi_response_format}`).

However there is still hope: If you reach a breakpoint and type `disassemble` in the terminal emulator at the bottom, you should get something close to what you're looking for. See the attached screenshot for what it looks like on my machine. 
![image](https://cloud.githubusercontent.com/assets/5715368/26287171/6301ccc8-3e2a-11e7-848b-d0b429f4e4f2.png)

Let me know if this helps.

**Comment by cs01** [comment]
@kryptoknight13, @ColdHeat the latest version of gdbgui drops to assembly if it can't locate the source code. Mind giving it a shot and letting me know if it's what you were looking for?

![image](https://user-images.githubusercontent.com/5715368/27621913-dc4f04a8-5b88-11e7-9440-e0787e09e630.png)

**Comment by cs01** [comment]
Since the new feature has been added and I have not heard anything back from @ColdHeat nor @kryptoknight13 the issue is being closed.
