### ISSUE TITLE
rust executables with gdb 7.12+ can't display register values (gdb bug)

### ISSUE THREAD

**Issue by cs01** [cs01/gdbgui#64]
The current workaround is to use gdb 7.11.1.

The error was first encountered by @sharazam in #52.

The message shown on the frontend is
```
error Error occured on server when running gdb command: [Errno 32] Broken pipe
```

**Comment by cs01** [comment]
Turns out gdb is the pipe is broken because gdb segfaults and the process exits (becomes defunct/zombie). The segfault only occurs when debugging a rust program under pygdbmi, not when running directly from gdb's commandline, or debugging any other language.

The dmesg log shows
```
[ 4467.187888] gdb[13609]: segfault at 0 ip 00000000006489ed sp 00007ffc0a0ce260 error 4 in gdb[400000+617000]
```

Running again with strace output logged yields this as the last line. 

```
ptrace(PTRACE_GETREGSET, 14037, NT_X86_XSTATE, [{0x7ffe8bb4ee20, 832}]) = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0} ---
+++ killed by SIGSEGV +++
```

See attached file [gdb_strace.txt](https://github.com/cs01/gdbgui/files/966855/gdb_strace.txt) for the full strace log.

**Comment by sharazam** [comment]
Interesting. Didn't expect a segfault to be the reason. Will be watching this.

**Comment by cs01** [comment]
The segfault occurs in `-data-list-register-values x` regardless of whether it's run as a subprocess or not. The bug was fixed in gdb's [git repository](git clone git://sourceware.org/git/binutils-gdb.git), commit b96645f1a1e608 "Add support for untagged unions in Rust". 

The HEAD of gdb's master branch does **not** have this bug, so the next gdb release (version 8) should have this issue fixed. For now, I will add a warning to gdbgui, and disable the `-data-list-register-values x` if gdbgui was able to determine rust source files were used to compile the executable.

Bug filed with gdb: https://sourceware.org/bugzilla/show_bug.cgi?id=21450

**Comment by cs01** [comment]
@sharazam I added logic to prevent gdbgui from fetching register values when using gdb 7.12.x and debugging a rest executable, which avoids the segfault. gdbgui also displays a warning to users that this is occurring.

**Comment by o11c** [comment]
Can you still fetch the values using `-var-create $registername`?

**Comment by cs01** [comment]
Doesn't seem to be valid syntax:
```
-var-create rax
-var-create: Usage: NAME FRAME EXPRESSION.
```
however `info registers` works
```
info registers
rax 0x7fffffffdfd0
 140737488347088

rbx 0x0
 0

rcx 0x604028
 6307880
```
