### ISSUE TITLE
Unable to use -r

### ISSUE THREAD

**Issue by jeaye** [cs01/gdbgui#69]
```bash
┌─(✓)[jeaye@oryx]─[~][23:42:27]
└──╼ gdbgui -p 5001 -r
Traceback (most recent call last):
  File "/sbin/gdbgui", line 11, in <module>
    load_entry_point('gdbgui==0.7.6.2', 'console_scripts', 'gdbgui')()
  File "/usr/lib/python3.6/site-packages/gdbgui/backend.py", line 385, in main
    setup_backend(serve=True, host=args.host, port=int(args.port), debug=bool(args.debug), open_browser=(not args.no_browser), LLDB=(args.lldb or 'lldb-mi' in args.gdb.lower()))
  File "/usr/lib/python3.6/site-packages/gdbgui/backend.py", line 106, in setup_backend
    print('\n\n** view app at http://%s:%d **\n\n' % (socket.gethostbyname(socket.gethostname()), port))
socket.gaierror: [Errno -2] Name or service not known
```

I was originally trying this in a vagrant machine, which has port 5000 forwarded to my host. When it failed, I tried it on the host, where I can also reproduce the issue. I'd think that binding to `0.0.0.0` shouldn't cause any problems, but I may be missing something.

Tested on Arch Linux.

```bash
┌─(✗)[jeaye@oryx]─[~][23:42:31]
└──╼ python --version
Python 3.6.1
┌─(✓)[jeaye@oryx]─[~][23:44:52]
└──╼ pip --version
pip 9.0.1 from /usr/lib/python3.6/site-packages (python 3.6)
```

**Comment by Skince** [comment]
This is probably not related to gdbgui. 
Maybe there's something wrong with your /etc/hosts ?

**Comment by cs01** [comment]
The exception is raised when running `gethostbyname`, which occurs *before* it tries to serve on `0.0.0.0`.
From [python 2 documentation](https://docs.python.org/2/library/socket.html#socket.gethostname) (emphasis mine):
> socket.gethostname()
Return a string containing the hostname of the machine where the Python interpreter is currently executing.
If you want to know the current machine’s IP address, you may want to use gethostbyname(gethostname()). **This operation assumes that there is a valid address-to-host mapping for the host, and the assumption does not always hold.**


Like @Skince said, this is probably related to `/etc/hosts`. If you look at the output of 
```
python -c "import socket; print(socket.gethostname())"
```
is it (the hostname) found in the file `/etc/hosts`? I am guessing it's not. In any case, `gdbgui` should not assume it is, so I will put a fix in to avoid this.

Thanks for filing a bug report.

**Comment by jeaye** [comment]
Looks like `/etc/hosts` specifies only `localhost`, but `socket.gethostname()` is returning the value of `/etc/hostname`. I agree that `gdbgui` should not assume this, so I appreciate the fix.

Thanks for the quick replies. :)

**Comment by cs01** [comment]
What do you mean by "socket.gethostname() is returning the value of /etc/hostname".

The return value is `/etc/hostname`?

**Comment by jeaye** [comment]
I mean that `python -c "import socket; print(socket.gethostname())"` and `cat /etc/hostname` output the same value.

```bash
┌─(✓)[jeaye@oryx]─[~][10:22:14]
└──╼ cat /etc/hosts
#
# /etc/hosts: static lookup table for host names
#

#<ip-address>	<hostname.domain.org>	<hostname>
127.0.0.1	localhost.localdomain	localhost
::1		localhost.localdomain	localhost

# End of file
┌─(✓)[jeaye@oryx]─[~][10:22:27]
└──╼ cat /etc/hostname
oryx
┌─(✓)[jeaye@oryx]─[~][10:23:28]
└──╼ python -c "import socket; print(socket.gethostname())"
oryx
```

**Comment by cs01** [comment]
Ah sorry, gotcha. I'm not sure that is relevant since I don't think it affects the address-to-host mapping.

**Comment by jeaye** [comment]
Gotcha, thanks.

**Comment by cs01** [comment]
@jeaye can you confirm the fix worked and close (it's on the master branch, not through pip)? If not, just let me know and I will close out myself. Thanks.

**Comment by jeaye** [comment]
@cs01 master with `-r` is working for me! Thank you.
