### ISSUE TITLE
please provide steps for debugging of a .cpp source file

### ISSUE THREAD

**Issue by yolob21** [cs01/gdbgui#73]
running win7 with cygwin64 installed and python 2.7 as an environment in anaconda.

I am lost as to how to view the source code in the browser and debug it. I went through the screenshots and gif. A small guide of sorts from loading a .cpp file to debugging it would be really helpful.

**Comment by cs01** [comment]
I have been meaning to make some youtube video demos, but until then hopefully this will help:

- Type `gdbgui` in your terminal
- Open your browser and navigate to the ip/port that gdbgui is being served on (i.e. `localhost:5000`) if it did not open automatically
- Type the path to the executable in the input at the top (next to "Load the Binary and Args"). The executable should already exist and have been compiled with the `-g` flag.
- Click `Load the Binary and Args`. The program should be loaded (but not running!) and the source code should be displayed in the large empty box. If it's not, make sure you compiled your program with the `-g` flag
- Click the `Run` button, which is on the top right and looks like a circular arrow
- Step through the program by clicking the `Next`, `Step`, `Continue`, etc. as desired. These are also on the top right.

If you need any more help or if this isn't working let me know.

**Comment by cs01** [comment]
@yolob21 I added these instructions to the main readme file
