### ISSUE TITLE
Install on a server without admin rights

### ISSUE THREAD

**Issue by anandvis** [cs01/gdbgui#74]
This tool looks really good and I am itching to try it out. Wanted to find out if there was a way to install it on a linux server where I dont have admin rights, say for instance within my home directory. Thanks for your help!

**Comment by cs01** [comment]
Yes absolutely! 

Try `pip install gdbgui --upgrade --user`.

From the pip documentation:

```
  --user                      Install to the Python user install directory for your platform. Typically ~/.local/,
                              or %APPDATA%\Python on Windows. (See the Python documentation for site.USER_BASE for
                              full details.)
```

Let me know if that works.

**Comment by cs01** [comment]
You can also email me grassfedcode@gmail.com if you want more help. 

If you get it working feel free to close this ticket.

**Comment by cs01** [comment]
@anandvis did this work for you? Feel free to close if it did.

**Comment by jounathaen** [comment]
Installation worked for me on a server without admin rights. Although it does not run. It says:
```
exit gdbgui by pressing CTRL+C
/usr/bin/xdg-open: line 402: htmlview: command not found
```

**Comment by cs01** [comment]
Can you copy+paste the command you ran and its output?  

Judging by the error it looks like there was an error opening the browser. You may want to try `gdbgui -r` (run on remote machine) or `gdbgui -n` (suppress browser from opening).

**Comment by cs01** [comment]
Try this:

```
curl https://raw.githubusercontent.com/mitsuhiko/pipsi/master/get-pipsi.py | python
pipsi install gdbgui
gdbgui
```
