### ISSUE TITLE
No GDB console on Firefox

### ISSUE THREAD

**Issue by noscript** [cs01/gdbgui#75]
Console is visible in Chrome but not in Firefox 54.

**Comment by cs01** [comment]
This is due to CSS that is handled differently between Chrome/Firefox. I would like to fix this, but for now Firefox is not listed as a supported browser of gdbgui.

**Comment by mestaritonttu** [comment]
What are the specific problems? I skimmed through https://github.com/cs01/gdbgui/blob/master/gdbgui/static/css/gdbgui.css but could not find anything that stuck out.
This test did not complain anything about Firefox (but maybe it is outdated): https://www.browseemall.com/Compatibility/ValidateCSS

**Comment by cs01** [comment]
I think it has to do with the splitjs library, but I can't say I know the exact problem. It has to do with a combination of gdbgui.pug, gdbgui.js (the split.js part at the bottom), and gdbgui.css.

**Comment by fluks** [comment]
The generated HTML contains some errors, it isn't valid if you try to validate it, using W3C validator, for example. Using this fixed [gdbgui.pug] template(https://gist.github.com/fluks/7468e62ef15df1795239494fa72ce03b), the console becomes barely visible on the right side of the page. The same happens in Chrome, btw.

**Comment by cs01** [comment]
@fluks thanks. I added the `doctype html` tag which makes Chrome and Firefox render the same (both poorly). I am getting close to a fix and hope to have it merged sometime tonight.
