### ISSUE TITLE
Commands like -var-create, print and breakpoint don't need jump to current line.

### ISSUE THREAD

**Issue by wuyihao14** [cs01/gdbgui#78]
Method `highlight_paused_line_and_scrollto_line` is frequently called. Sometimes it's unnecessary, and annoying.

**Comment by cs01** [comment]
I noticed this recently when hovering over a variable.  I'll make it jump to the line only when one of the program control buttons is pressed (run, next, step, etc).

**Comment by cs01** [comment]
I didn't do this yet, so I don't want to close it. 

Also if you have any other suggestions about things that are annoying please let me know! Either create a ticket or email me.
