### ISSUE TITLE
Expressions unable to cope with altered container size

### ISSUE THREAD

**Issue by wuyihao14** [cs01/gdbgui#79]
An STL container expression, e.g. `list1`, {1}, with size 1,
after it's updated to {2,3}, with size 2,
the expressions bar only displays the updated 1st element,
but leaves out the 2nd new element.

**Comment by wuyihao14** [comment]
This bug is resulted from this line

[, obj = Expressions.get_obj_from_gdb_var_name(expressions, changelist.name)
](https://github.com/cs01/gdbgui/blob/master/gdbgui/static/js/gdbgui.js#L2518)

After receiving gdb response of change_list. The existing child expressions get updated. However those not existing line failed on this line. And `_.assign(obj, changelist)` actually assigns the parent node, which introduces a bug.

**Comment by wuyihao14** [comment]
#82

**Comment by wuyihao14** [comment]
However this failed on this condition:

Empty Container --> Container with one element.

**Comment by cs01** [comment]
Is this is a limitation of gdb?

Should the PR be merged as is?

**Comment by wuyihao14** [comment]
Not sure about this another bug  yet, or has it been fixed.

But the `change_list->new_children` bug is indeed fixed. It's **NOT** a gdb limitation, but a front-end bug.

**Comment by cs01** [comment]
@wuyihao14 I would recommend filing a bug report against gdb for the issue of `empty -> 1 element` not showing up in the changelist.

https://sourceware.org/bugzilla/

Thanks again for the fix that you made.

**Comment by wuyihao14** [comment]
I was wrong about this `empty -> 1element` bug. In this case, gdb returns a changelist with `has_more == 1` (I suppose this means this variable be expanded ?) but no `new_children`.

Can you give me advice on how to expand them ? Or someone more capable should fix this.

**Comment by cs01** [comment]
As you probably saw, gdbgui uses `-var-update --all-values *` to update the values of all expressions every time the program pauses. gdb documents its machine interface at https://sourceware.org/gdb/onlinedocs/gdb/GDB_002fMI-Variable-Objects.html. The two relevant pieces from this documentation are below.

It looks like the right way to do this is to run `-var-set-update-range <varname> <numchildren> <new_num_children>` whenever `has_more` is true.

> ‘has_more’
> This is an integer value, which will be 1 if there are more children available outside the varobj’s update range.


> The -var-set-update-range command
> 
> Synopsis
> 
>  -var-set-update-range name from to
> Set the range of children to be returned by future invocations of -var-update.
> 
> from and to indicate the range of children to report. If from or to is less than zero, the range is reset and all children will be reported. Otherwise, children starting at from (zero-based) and up to and excluding to will be reported.
>
> Example
> 
> (gdb)
> -var-set-update-range V 1 2
> ^done
> 

I am happy to do this if you don't feel comfortable adding it. Of course if you want to try, you are welcome to. Just let me know. If you want me to do it, could you provide the source code that's causing this issue so I can test it myself?

**Comment by wuyihao14** [comment]
Thanks. I gave it a try. #86 
I think I fixed this somehow.
If you're satisfied with it. I think this issue can be closed.

**Comment by cs01** [comment]
I tested it with c++ vectors and it worked perfectly. Nice work. Feel free to close.

**Comment by wuyihao14** [comment]
Thanks again for your help!
