### ISSUE TITLE
Disassembly fetch doesn't work from within vagrant

### ISSUE THREAD

**Issue by jeaye** [cs01/gdbgui#88]
When I run gdbgui from within a vagrant machine (running Arch), I can access the web UI just fine. I don't get any errors presented and I can tell that it finds the binary, since it doesn't show the "no file specified" error. When I click the "start inferior program from the beginning" button, the status label beneath it is updated to "stopped, exited." However, I cannot fetch any disassembly, set breakpoints, inspect memory, or anything useful. Checking the "automatically break on main" hasn't helped either, as the program just exits.

I'm running the gdb server like so:

```bash
# From within the vagrant machine
$ gdbgui -r
```

When I run the gdbgui from within my host Arch machine, not the guest Arch vagrant machine, I can load the same binary and fetch the disassembly. Both are using the same versions of all packages.

### Pip freeze
```bash
$ pip freeze
appdirs==1.4.3
click==6.7
enum-compat==0.0.2
eventlet==0.21.0
Flask==0.12.2
Flask-SocketIO==2.9.0
gdbgui==0.7.8.2
gevent==1.2.2
greenlet==0.4.12
itsdangerous==0.24
Jinja2==2.9.6
MarkupSafe==1.0
packaging==16.8
pygdbmi==0.7.4.0
Pygments==2.2.0
pyparsing==2.2.0
pypugjs==4.2.2
python-engineio==1.6.1
python-socketio==1.7.5
six==1.10.0
Werkzeug==0.12.2
```

### GDB versions
```bash
$ gdbgui -v
0.7.8.2

$ gdb --version
GNU gdb (GDB) 7.12.1
...
```

### OS/Browser
* Arch Linux x86_64
* Firefox 54 (64bit)

**Comment by cs01** [comment]
Firefox is not officially supported at this time by gdbgui.  If you use chrome, the console widget will be visible and you may see some error messages in it. 

After loading the program, run the command 'info target' in vagrant as well as the host machine to see if the list of files used to load the symbols tables is the same.

**Comment by jeaye** [comment]
Oh, I see. I'm not open to using proprietary browsers, but I certainly look forward to when Firefox is supported. Thanks for the quick reply.

**Comment by cs01** [comment]
How about chromium?

**Comment by jeaye** [comment]
I could install Chromium to help debug this issue, but I won't be keeping it just to order to use gdbgui.

After installing Chromium, I can verify that this issue doesn't exist. Furthermore, I can actually see the gdb console, etc. Please do support Firefox. :)

**Comment by jeaye** [comment]
I'll close this ticket, since the issue has nothing to do with vagrant or anything else I described, it seems. There are already other tickets, I see, mentioning the lack of Firefox support.

Thanks, again, for the quick replies.

**Comment by cs01** [comment]
Interesting, I am surprised the issue disappeared completely when switching browsers.  Totally understand about the browser.  I'm typing this from Firefox myself.  Getting Firefox to work has been challenging.  I tried and failed 3 times now, but nevertheless it is on my shortlist to get fixed.
