### ISSUE TITLE
how to stop running program?

### ISSUE THREAD

**Issue by mmccoo** [cs01/gdbgui#90]
I feel silly for asking, but is there a way to stop an already running program?

In cmdline gdb, I just do ctrl-c and the program stops wherever it is.

I don't see a similar function in gdbgui.

**Comment by cs01** [comment]
This is not a dumb question.

What you can do is stop at a breakpoint and run the command  `signal 2` (`SIGINT`) in the gdb command line widget, which is equivalent to CTRL+C in the terminal. It might work when running in realtime, but I haven't tested it.

There is also the command `-exec-interrupt` (ftp://ftp.gnu.org/pub/old-gnu/Manuals/gdb/html_chapter/gdb_22.html) but it doesn't seem to work.

Let me know if either of these work for you.

**Comment by duststorm** [comment]
I'm interested in this functionality too.
With the current version, as long as no breakpoints are hit, you lose the ability to control gdb. If no future breakpoints are hit you're left without control.
Having a simple pause button at the top of the screen would go a long way in improving matters.
I saw your work in the rewrite-to-react branch, but when I checked out the code I could not immediately find an obvious button in the gui. What's the status of your work?

**Comment by cs01** [comment]
@duststorm the `rewrite-to-react branch` (commit e3e1d9a95bc7) has more features and no known regressions from the latest master, so it's safe to use.

On that branch, at the top right of the side pane there are some new buttons:
![image](https://user-images.githubusercontent.com/5715368/31348353-3ff69204-acd4-11e7-849c-812b07cf283d.png)

If you click `send to inferior`, it'll send the selected signal to the inferior process, which usually causes it to exit entirely. After doing a little searching, it looks like pausing a running program might be possible by sending `SIGINT` to gdb itself. I will do look into that more and add a button to do that as well if it makes sense. 

Let me know if the branch helps at all.
