### ISSUE TITLE
Is gdbgui compatible with pwndbg

### ISSUE THREAD

**Issue by 3m0W33D** [cs01/gdbgui#96]
Hi is gdbgui compatible with pwndbg?

https://github.com/pwndbg/pwndbg

gdbgui doesnt seem to be able to use pwndbg features for me.

Is it possible to integrate it in?

**Comment by cs01** [comment]
gdbgui prints out all output from gdb to the terminal widget in the frontend, so there's no real reason it can't work. It doesn't seem to work though. I downloaded and tried to use it, and got these sorts of errors:

```
\e[31mException occured: Error: Cannot access memory at address 0x4000000000400000 (<class 'gdb.MemoryError'>)\e[0m
\e[35mFor more info invoke `\e[0m\e[33mset exception-verbose on\e[0m\e[35m` and rerun the command\e[0m
\e[31mException occured: Error: Cannot access memory at address 0x4000000000400000 (<class 'gdb.MemoryError'>)\e[0m
\e[35mFor more info invoke `\e[0m\e[33mset exception-verbose on\e[0m\e[35m` and rerun the command\e[0m
\e[31mException occured: Error: invalid literal for int() with base 10: ',value="15"' (<class 'ValueError'>)\e[0m
\e[35mFor more info invoke `\e[0m\e[33mset exception-verbose on\e[0m\e[35m` and rerun the command\e[0m
```

With verbose output, I get this:
```
Traceback (most recent call last):
File "/home/csmith/git/pwndbg/pwndbg/events.py", line 119, in caller
func()
File "/home/csmith/git/pwndbg/pwndbg/memoize.py", line 48, in __call__
value = self.func(*args, **kwargs)
File "/home/csmith/git/pwndbg/pwndbg/stack.py", line 127, in is_executable
for phdr in pwndbg.elf.iter_phdrs(ehdr):
File "/home/csmith/git/pwndbg/pwndbg/elf.py", line 176, in iter_phdrs
phnum, phentsize, phdr = get_phdrs(ehdr.address)
File "/home/csmith/git/pwndbg/pwndbg/elf.py", line 169, in get_phdrs
x = (phnum, phentsize, read(Phdr, Elfhdr.address + phoff))
File "/home/csmith/git/pwndbg/pwndbg/elf.py", line 59, in read
data = pwndbg.memory.read(address, size)
File "/home/csmith/git/pwndbg/pwndbg/memory.py", line 44, in read
result = gdb.selected_inferior().read_memory(addr, count)
gdb.MemoryError: Cannot access memory at address 0x4000000000400000
```

One difference is that gdb is run as a python subprocess, not directly from the shell. Not sure if this matters. Any ideas @zachriggle, @disconnect3d? It'd be nice if the project was compatible. pwndbg is very cool, btw.

**Comment by disconnect3d** [comment]
@cs01 Can you provide some more information on your example?

Like particular binary, gdb/python/pwndbg version (e.g. use `version` pwndbg command).

I mean, I managed to debug launch gdbgui along with pwndbg for:
* /bin/ls
* a hello world like binary

I am not saying it is working "well" but it is not crashing for me:
https://i.gyazo.com/44d94394a6318fa9de273d5063ffceec.png

It seems that we - Pwndbg - should provide an option to prevent output from being colored.

**Comment by cs01** [comment]
I'm running a hello world type binary as well (source code below).

```
version
\e[91mGdb: GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.3) 7.7.1\e[0m
\e[91mPython: 3.4.3 (default, Nov 17 2016, 01:12:14) [GCC 4.8.4]\e[0m
\e[91mPwndbg: 1.0.0 build: f481201\e[0m
```

gdbgui version  0.7.9.1.

> It seems that we - Pwndbg - should provide an option to prevent output from being colored.

Agreed, should be easy enough to call a different colorize function if `isatty()` is false, but I am more interested in the `Cannot access memory at address` errors.

```
#include <stdio.h>

struct my_type_t {
    int a;
    float b;
    struct {
        size_t c;
        double d;
    };
};

/* Forward declaration */
void bye();

int main()
{
    printf("hello world\n");
    struct my_type_t myvar= {
        .a = 1,
        .b = 1.2,
        .c = 4,
        .d = 6.7
    };
    int i = 0;
    for(i = 0; i < 1; i++){
        printf("i = %d\n", i);
    }
    bye();
}
```
