### ISSUE TITLE
issue about dependency python-flask 

### ISSUE THREAD

**Issue by ZWindL** [cs01/gdbgui#97]
When I debugging a binary I met this:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 658, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 972, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 863, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (Flask 0.12.2.dev0 (/usr/lib/python3.6/site-packages), Requirement.parse('Flask>=0.12.2'), {'gdbgui'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/gdbgui", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3049, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3033, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3062, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 660, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 673, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 858, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'Flask>=0.12.2' distribution was not found and is required by gdbgui
```
my distro is Arch Linux and all the packages are up to date, the version of `python-flask is` `0.12.2` but I still got that problem.

There's another user who met that too: https://aur.archlinux.org/packages/python-gdbgui

I haven't tried on other platforms or distros, and I'm not sure it's my PKGBUILD's problem.

**Comment by muttleyxd** [comment]
Editing this file makes it work:
/usr/lib/python3.6/site-packages/gdbgui-0.7.9.1-py3.6.egg-info/requires.txt

I just changed required version to >=0.11 and it runs - seems like 0.12.2.dev0 seems smaller than 0.12 to Python's version comparing method. 

Is that a bug in Python? Unfortunately I don't know much Python, so I'm not sure if requirement checking function is included in Python or in gdbgui.

**Comment by cs01** [comment]
If I create a clean virtual environment on my computer and run `pip install gdbgui --upgrade` it installs with no problem. 

This seems to be some kind of environment issue, not something specific to gdbgui. Could you provide instructions for me to recreate the error? Did you use the `--upgrade` flag when using `pip`?

**Comment by ZWindL** [comment]
@cs01 Thanks for your relpy.
I didn't install it with `pip` but with `pacman`; I create that package for convenient Arch user easy to manage it.
And there is the [PKGBUILD](https://gist.github.com/ZWindL/e49d05e4a4e1873b1d9d9d77867aec5e) .

And here is my `pipconflictchecker` result:
```
--------------------------------------------------
 Conflicts Detected
--------------------------------------------------
 - Flask(0.12.2.dev0) gdbgui(>=0.12.2)
```

**Comment by cs01** [comment]
@ZWindL you'll need to find a way in `pacman` to replace Flask 0.12.2.dev0 with Flask 0.12.2. After that, everything should work fine. I think I specified 0.12.2 because it was the latest version, but gdbgui will work with any version of flask that's compatible with flask-socketio (https://github.com/miguelgrinberg/Flask-SocketIO/blob/master/setup.py), so it looks like Flask >= 0.9 will do.

**Comment by ZWindL** [comment]
@cs01 OK, thanks, I've already changed the dependency package from `python-flask` to `python-flask-git`, the git version is 0.12.3, so it will be fine.
